### ISSUE TITLE
Menu item main page url trailing slash revisited after 3.7.0

### ISSUE THREAD

**Issue by sailinf** [qtranslate/qtranslate-xt#743] opened 2019-10-11 16:32 UTC
After installing 3.7.0, I wanted to redo the modification from #660 . Seems the line location has moved to line 340 in the file qtranslate_frontend.php but for some reason I could not get the fix suggested by @bagaweb to work anymore.  I have no idea why not as the surrounding code looks just the same as previously?

I know this is a dependence with Qt Slug but thought I'd raise the issue as a placeholder.

**Comment by herrvigg** [comment] 2019-10-11 19:38
Mmmm  that would be surprising. All the recent changes are not supposed to change anything for QT-slug. Did this work with 3.6.3? What is the problem exactly?

I don't use slug, but i've installed it (from this [github](https://github.com/not-only-code/qtranslate-slug) - i hope it's the good version!) so i can search in the code and see what they use before refactoring some parts in QT-XT. Until now i avoided doing radical changes in the API (PHP classes, hooks and JS API), i've been removing a few things that i considered obsolete or not used by anyone, since the most crucial plugins are now merged as modules. Those changes are always mentioned in the changelog though.

I've always tried to keep the retro-compatibilty with QT-slug. For example, QT-slug uses `url_info[original_url]` so i left it exclusively for this plugin.

**Comment by sailinf** [comment] 2019-10-11 19:48
My coding is so limited so could be my fault as well, but as I reported under the slug request, I'm also seeing some other issues specifically related to menus. Didn't look for this for 3.6.3, so not sure. I can go back to that version on my test site when I find a little time.

**Comment by herrvigg** [comment] 2019-10-11 20:01
But those issues for the menus were not something new, right? Currently my concern for QT-slug is just not introducing new regressions, let's focus only on this now. The problem is that this plugin has not been maintained for 3 years so there's certainly some work to do to get it back on tracks. It's around 5000 lines of code, not huge but still a not tiny one.

**Comment by sailinf** [comment] 2019-10-11 20:15
Yes, some of the things are new.

**Comment by herrvigg** [comment] 2019-10-11 20:26
With the releases [archives](https://github.com/qtranslate/qtranslate-xt/releases), you can always revert to a previous version quite easily. There should not be any risk doing so because the core functions and the formats have remained the same (version 3). From this you can better track when a regression comes. Keep in mind other things might also have changed like WP, browser, other plugins, ...

**Comment by sailinf** [comment] 2019-10-12 09:26
Yes, but choosing between getting the data loss problem fixed and some issues with the menus, 3.7.0 is the right choice for me. Just keeping the hope for an integrated slug alive :-)

**Comment by herrvigg** [comment] 2019-10-12 11:04
Well i still don't even know what it is about so it would be a difficult 😅 
Did you try with the previous version 3.6.3? I don't see why the last changes would impact this, there is no direct relation from my point of view. 
Even more, are you sure this is related to slug? I think there a few minor bugs with the menus.
Please describe the problem accurately with maximum of information about the context.

**Comment by herrvigg** [comment] 2019-10-15 21:11
That's great news! It really surprised me that the last changes had any effect on -slug as i even avoided some changes on purpose for it. If @sailinf can confirm there is no regression you can close this ticket.

**Comment by herrvigg** [comment] 2019-10-20 22:17
Hopefully this is solved, except the fact you always have to redo the change at every release. Discussion follows in #671.

**Closed by herrvigg** 2019-10-20 22:17 UTC
Labels: integration
