### ISSUE TITLE
Last ACF Update broke standard fields automatic conversion

### ISSUE THREAD

**Issue by ProtSport** [qtranslate/qtranslate-xt#1212] opened 2022-08-16 20:44 UTC
![help2](https://user-images.githubusercontent.com/34627975/184982104-a6523f39-5901-494a-b57a-2d88af4f8c61.png)
Hello 

It seems like the latest ACF, while "convert standard fields" is checked in ACF-Qtranslate settings, does not bind anymore to standard Qtranslate functions.

I have issue on setting page ACF -   acf-input, underscore, qtranslate-admin-main (missing) | (wp-content/plugins/qtranslate-xt-master/dist/modules/acf.js)

![help](https://user-images.githubusercontent.com/34627975/184981529-19d0307f-84c8-4a5c-a978-f87377a60d7b.png)

**Comment by herrvigg** [comment] 2022-08-18 21:54
I'm not able to reproduce this problem, but I'm using the free version ACF 5.12.3. 
However the error you show with the missing dependency is strange, it doesn't seem to be a problem in the ACF part but the main `qtranslate-admin-main` script, which is not depending on ACF. It's the other way around, the ACF script is depending on this. So if this doesn't load, the ACF code cannot work as intended. So it may come from something else?

**Comment by herrvigg** [comment] 2022-12-23 11:06
Many ACF fixes released in 3.13.0. Please retry with that version and re-open the ticket if it's still the case.

**Closed by herrvigg** 2022-12-23 11:06 UTC
Labels: need info, module: ACF
