### ISSUE TITLE
No LSB on categories with NextGen Gallery

### ISSUE THREAD

**Issue by xtheking2019** [qtranslate/qtranslate-xt#643] opened 2019-02-01 17:42 UTC
I can't translate categories as LSB buttons are not available on categories. Also "inyMCEPreInit is not defined error" appeared.
I tried to switch to raw editor mode and it works... but not a good solutions.
WP 5.0.3 + Qtranslate-xt installed.
thank you

**Comment by herrvigg** [comment] 2019-02-12 13:55
"TinyMCEPreInit is not defined error" is definitely not a good thing, the translations won't work if the script doesn't load correctly. For me it works. You might have something else conflicting. Can you check better in the console and see if there are other errors?

**Comment by herrvigg** [comment] 2019-03-10 11:44
@xtheking2019 we'd need more details about this or we won't be able to do much more and i'll have to close this. Somehow it could be related to https://github.com/qtranslate/qtranslate-xt/issues/650 but here is looks a bit different.

**Comment by xtheking2019** [comment] 2019-03-11 11:32
Dear Herr Vigg,
I noticed there is a big problem with Nextgen Gallery. If you have this
plugin activated, all languages are gone...
Also there is a big problem with menus and categories.
regards
xavi

Missatge de Herr Vigg <notifications@github.com> del dia dg., 10 de març
2019 a les 12:44:

**Comment by xtheking2019** [comment] 2019-03-14 16:59
All times I install qtranslate and nextgen gallery happens... also if I
disable  nextgen gallery it works again.

regards

xavi

Missatge de xavier guimera <xguimera@gmail.com> del dia dl., 11 de març
2019 a les 12:32:

**Comment by herrvigg** [comment] 2019-03-14 23:50
I just tested with NextGen Gallery, it seems to works fine. Can you tell me the errors you get in the Web Console?

![image](https://user-images.githubusercontent.com/19155375/54398603-0a785e00-46bb-11e9-9471-6d21544094f6.png)

**Comment by xtheking2019** [comment] 2019-03-15 14:45
https://www.fare-auto.com/sci/wp-admin
@adminSCI
H9hTUg$yKAy3mDXM3m

try and let me know.

if you try to access to post categories you will see...

thank you

Missatge de Herr Vigg <notifications@github.com> del dia dv., 15 de març
2019 a les 0:50:

**Comment by herrvigg** [comment] 2019-03-15 20:33
Oh my bad i didn't understand it was specifically for the categories. But that's great you could relate it to NextGen Gallery. And now i can reproduce it directly on my platform! So now i can debug this more easily. Thanks! I'll keep you updated.

**Comment by herrvigg** [comment] 2019-03-16 11:24
@xtheking2019 OK i found the problem! In fact there's something weird only happening with NGG, it loads a TinyMCE for the categories (who knows why?!) but it's not loaded via a TinyMCEPreInit object, unlike the general case in WP for the post.

Anwyway i could fix it and it now works on my setup. You can try it by checking out the git branch `fix-ngg-categories`or by downloading this (just rename your existing qtranslate-xt before this):
:https://github.com/qtranslate/qtranslate-xt/archive/fix/js-ngg-categories.zip

If it also works for you i will merge and probably release it soon as hotfix.

**Comment by xtheking2019** [comment] 2019-03-16 11:35
That's perfect!!!

I will try on Monday.

Also I found that if I have lot +100 categories sometimes traslations goes
crazy... Don't know if it's also when using NGG

Regards

Xavier Guimerà

**Comment by herrvigg** [comment] 2019-03-19 23:02
@xtheking2019 could you try this patch? I will certainly merge it soon but it would have been good to have your feedback on this.

**Comment by xtheking2019** [comment] 2019-03-20 10:36
I will give you feedback asap. I am now in other project... asap as I go
back to old project I will see

I noticed some other things... after being using your plugin during lot of
time... maybe will help you in development...

1. if you delete a language after enter information I found lot of
[:old_language] in database
2. if you use more than 100 post categories the plugin rename some of them
when you edit and crosses languages descriptions.... really crazy...
3. the language menu does not use current_language if you disable /language
in default language
4. category slug by language is not being used... this would be very
nice... as categories are only traslated to 1 language...

regards

xavi

Missatge de Herr Vigg <notifications@github.com> del dia dc., 20 de març
2019 a les 0:02:

**Comment by herrvigg** [comment] 2019-03-20 11:11
Yes there is a certainly a need of new features for maintenance and cleaning the DB on the long run, but i will not look at those for now. A good DB admin should be able to sort this out on his own with SQL queries. If we do it in qTranslate it has to be extremely well tested so a lot of things are required before being able to do that.

**Comment by xtheking2019** [comment] 2019-03-20 11:17
nice!

If you need any developer to test I can help you (also with others you may
need)

I develope websites with custom templates... and always use your plugin...

regards

xavi

Missatge de Herr Vigg <notifications@github.com> del dia dc., 20 de març
2019 a les 12:11:

**Comment by xtheking2019** [comment] 2019-03-20 16:36
I have been testing your plugin and now it's ok!

thank you

Missatge de Herr Vigg <notifications@github.com> del dia dc., 20 de març
2019 a les 12:11:

**Comment by herrvigg** [comment] 2019-03-20 21:16
Good! Fix now merged.

**Closed by herrvigg** 2019-03-20 21:16 UTC
Labels: bug, integration

**Comment by marampb78** [comment] 2019-06-08 09:47
Hey xtheking2019. I was looking for a similar issue, where on a textarea with tinymce i actually cannot correctly edit the languages from the front end. this is why I actually arrived on your post. 
One big advice for you... In one of your original posts You provide the user and the password. This is really not a good idea. Even worst the password is still working on your site. My recommendation is that you change this as soon as possible, otherwise you risk loosing your data, or have your site hacked. For sure it will NOT be me who will hack you site, but there are tons of people with bad intentions in this world.
regards.

**Comment by xtheking2019** [comment] 2019-06-08 09:55
Nice! I just changed pwd...

I have a fixed copy of plugin... I don't know if they made changes to fix
error.

If you want I can send you this copy to test if you resolve

Please let me know and thanks

Xavier Guimerà

El ds., 8 de juny 2019, 11:47, marampb78 <notifications@github.com> va
escriure:

**Comment by herrvigg** [comment] 2019-06-08 13:27
Ahah i didn't even react about the password :P

@marampb78 wrote:
> I was looking for a similar issue, where on a textarea with tinymce i actually cannot correctly edit the languages 

Just for precision: the bug mentioned here was specific to the **categories** page with this message "TinyMCEPreInit is not defined error". The fix was released some time ago in qTranslate-XT 3.5.5. The bug was seen with NGG Gallery but it might be the case with other plugins, though it's very unlikely because they do quite nasty things with TinyMCE. If you have other issues, on other pages or other error message, it's a different topic so create a new issue in that case.

**Comment by marampb78** [comment] 2019-06-08 18:06
thanks a lot guys.  I already downloaded the latest version from github. 
i don't have the error activated, i suppose the problem is different.
Actually my issue is a little different. I actually succeeded to integrate the plagin with almost everything. I use the woffice theme and tinymcs advanced as editing plugin. All is fine when i edit a post from the backend, i'm using the language buttons for this. However when i'm in the frontend i do not have the language buttons, and when i write for example [:en]English text[:fr]Texte Français[:] and save - i see the correct language. If i reopen for editing the given post - it will only keep the current displayed language in occurence either Texte Français or English text. The tinymce just eat my language shortcodes [:en] and [:fr]. If i'm saving the new version of the post - i lose the translation (if I saved for instance english - i will only have English text even if switching in French
I tried adding a filter in such way the text is interpreted as raw, but it doesn't work...
this might come from the theme woffice itself maybe in the actions it does when saving the post, or from the tiny mce... I don't actually know (due to my limited knowlege of wp and php)

**Comment by marampb78** [comment] 2019-06-08 18:14
herrvigg and team - i really appreciate your are taking in charge and improving this plugin. I was looking around to other and i consider your's being the best. It works with almost everything on my site (comporting bbpress, buddypress, directory, posts, wiki, pages, calendar, etc). And the most important - you are doing this for the community for free, not like other asking money every year...
Really PRO. Thanks guys!
