### ISSUE TITLE
Use Pre-Path Mode is disabled 

### ISSUE THREAD

**Issue by hubosh** [qtranslate/qtranslate-xt#828] opened 2020-04-26 09:40 UTC
I just activated qtranslate-xt in a website and I noticed that the Use Pre-Path Mode is disabled as you can see in the image below.

![image](https://user-images.githubusercontent.com/24465260/80303785-0b832680-87bb-11ea-9158-779d85d7a7fc.png)

Kindly assist

**Comment by herrvigg** [comment] 2020-04-26 09:51
Very much likely a duplicate of #821.

**Closed** 2020-04-26 09:51 UTC
Labels: duplicate
