### ISSUE TITLE
Translation is broken on ACF Options Pages [Admin]

### ISSUE THREAD

**Issue by ChristophJeworutzki** [qtranslate/qtranslate-xt#1243] opened 2022-11-01 12:32 UTC
The translation doesn't seems to work on [ACF Options Pages](https://www.advancedcustomfields.com/resources/options-page/) anymore. The Language Switching Buttons (LSB) are missing and also the inline language tabs on the field seems to be broken.

WP Version 6.0.3 — qTranslate-XT Version 3.12.1 — ACF Version 6.0.3 (Also testet with ACF Version 5.12.3)

<img width="1440" alt="Screenshot 2022-11-01 at 13 25 48" src="https://user-images.githubusercontent.com/30624279/199231893-53150c89-0dc5-4640-b02c-03707936313e.png">

**Comment by ChristophJeworutzki** [comment] 2022-11-01 12:33
#1233

**Comment by herrvigg** [comment] 2022-11-05 11:41
It seems to be available only in the PRO version... 😕 
At least we see it's not coming from the ACF upgrade 5->6.
I close this as duplicate of #1233, please follow the original ticket.

**Closed by herrvigg** 2022-11-05 11:41 UTC
Labels: plugin: ACF
