### ISSUE TITLE
Woocommerce products name in widgets

### ISSUE THREAD

**Issue by adryxxx** [qtranslate/qtranslate-xt#755] opened 2019-11-08 11:18 UTC
Hello and congratulations for the excellent work!
I used qtranslatex and found an error in the woocommerce widgets: the title of the product can be seen with the language tags.
Example: [: it] Red [: en] Red [:]

I replaced the plugin with the latest version of qtranslateXT but the problem is always there.
I did various tests to see if it is the theme but with any theme the result does not change.
Has anyone solved the problem?

WP version 5.2.4
PHP version 7.2.22

Thanks in advance!
Adriano

**Comment by herrvigg** [comment] 2019-11-10 10:17
The field is probably missing in the selectors for finding the translatable fields. Usually the integration is done through a JSON file (which i dislike) but in the case of WooCommerce it's done with the built-in module, here for the admin section: https://github.com/qtranslate/qtranslate-xt/blob/master/modules/woo-commerce/qwc-admin.php

You should find how to select this field and add it here. If it's only for display and not edition, add encoding = display.

More info about the features can be found in the specification of the JSON format (the PHP code is doing the same): https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration

**Comment by adryxxx** [comment] 2019-11-12 10:18
Thanks for the reply!
I identified the id of the field and inserted the code in the file you told me but the result does not change. Did I do something wrong?

$fields['product-title'] = array( 'jquery' => '.product-title', 'encode' => 'display' );

But in the front file should I insert something?

![screenshot-www vitaben it-2019 11 12-11_17_39](https://user-images.githubusercontent.com/57527637/68662956-1cf2b200-053e-11ea-84f9-b003dc0c5964.jpg)

**Comment by herrvigg** [comment] 2019-11-13 10:32
But did you add this field on the right form? First you need to select the right form, then the fields. For the widgets i don't know exactly where it is though.

The front file is only for the "normal" rendering of the pages out of the admin section.

**Comment by adryxxx** [comment] 2019-11-13 11:36
Looking good I noticed that unfortunately there is no specific widget module. I wouldn't know where to start. :(

**Comment by herrvigg** [comment] 2019-11-13 11:48
Currently the modules are only meant to support the integration with a specific plugin, not for handling the widgets. For those you might actually take a look at the JS part: https://github.com/qtranslate/qtranslate-xt/blob/master/admin/js/widgets-exec.js

Sorry, i won't have much more time for this.

**Comment by adryxxx** [comment] 2019-11-13 16:05
OK thanks anyway.

**Comment by adryxxx** [comment] 2019-11-15 10:14
Allow me a consideration:
unfortunately the plugin remains very limited if woocommerce widgets are not integrated. Who uses woocommerce uses its widgets 100%. I'm sorry to say this, but it's the truth. I've been using the plugin for a long time but now when I have to use woocommerce I'll use another plugin. Bye

**Comment by herrvigg** [comment] 2019-11-15 21:36
hello,
i have no much clue about this, it seems other users were able to use woocommerce without any big problem so i don't really know.
For all the integration with this kind of plugins, i really count on the community and you, the users, to come up with improvements. I personally don't use woocommerce, but i added what was the last plugin available. I can't work on all together, the core part is taking me already a lot of time. To be clear, I have really zero gain in that project. WordPress is a big and messy environment. It's up to you (not only you personally) to make the whole thing live together with all the plugins.

**Comment by benjibee** [comment] 2020-01-08 15:27
I'm running into this same issues with various areas / parts of WooCommerce and the WooCommerce Subscriptions premium plugin.

Thanks @herrvigg for the little guide, I'll see if I can help out here and maybe have a fix to contribute in the coming weeks. @adryxxx if you find a solid fix for this let me know!

**Comment by herrvigg** [comment] 2020-03-10 17:11
A few notes from @spleen1981 https://github.com/qtranslate/qtranslate-xt/issues/608#issuecomment-420820843

> FRONTEND:
> 
> "Products widget": Product names not being translated (entire string with square brackets is shown). Workaround: wrapping "$product->get_name()" inside __() function in woocommerce "content-widget-product.php" template, row 29, via child-theme override, will do the job.

https://github.com/qtranslate/qtranslate-xt/issues/608#issuecomment-439737898
> Products widget: for products with untranslated title, nothing is shown as title inside the widget for missing translation language.
> 
> Products widget: stucked in the previous language when changing, maybe is the same bug as it was for Cart widget.

PS: not sure if all applies here but i just regroup previous comments to close #608.

**Comment by herrvigg** [comment] 2020-05-03 20:52
@adryxxx @benjibee i don't understand the problem here. Widget is a bit of a generic term that is used in many places in WP so it's difficult to know what it is about without the right context.

Which screen is this issue about? Can you provide a screenshot?

**Comment by herrvigg** [comment] 2020-05-03 21:01
Is this problem a specific case for WC or is it just a duplicate of #616 where WC would just be a way to illustrate the following problem?
- works when used from /wp-admin/widgets.php
- but not from /wp-admin/customize.php

Can we better precise the scope of this issue?

**Comment by EasyEl** [comment] 2020-05-04 07:17
A solution is always quite easy as long as you use a child theme and are able to customize the templates.

childtheme/woocommerce/content-widget-product.php

It would not translate the product names properly so I changed this:
<span class="product-title"><?php echo wp_kses_post($product->get_name()); ?></span>

to this:
<span class="product-title"><?php echo wp_kses_post( __($product->get_name() )); ?></span>

The only other issue I found that it does some kind of internal caching which is not good. I do not unterderstand the woocommerce caching system and how to exclude widgets from it.

**Comment by benjibee** [comment] 2020-05-04 13:05
@herrvigg I likely should have opened a new issue as I wasn't seeing this with widgets but in various areas of the WooCommerce admin interface and within WooCommerce Subscriptions / Memberships. We ended up going with another solution but if I spot something else like this I'll open an issue with more detail / screenshots.

**Comment by herrvigg** [comment] 2021-02-06 21:12
hello,
as @erichk4 suggests, the change with #957 should/could fix this issue with the name non translated. We had a hook on the `product_title` but not on `product_get_name`. This is now merged in master. Could someone check if this solve the problem (at least for what you can see)?

**Comment by herrvigg** [comment] 2021-02-06 21:14
I just realized that any product field has a hook meant for `display` context which is exactly what we want in qTranslate, by opposition to other context such as storing in DB, which we don't want to alter in that case.

**Comment by spleen1981** [comment] 2022-04-01 08:05
confirmed, #957 fixes this issue.

**Closed by spleen1981** 2022-04-01 08:05 UTC
Labels: plugin: WC
