### ISSUE TITLE
Custom fields translation losing after few days problem in admin of Houzez theme

### ISSUE THREAD

**Issue by zbubicic** [qtranslate/qtranslate-xt#849] opened 2020-06-07 18:32 UTC
Dear Sirs, after last update of Houzez theme https://themeforest.net/item/houzez-real-estate-wordpress-theme/15752549/comments?page=267 I made, they open new option Translation in Theme options, but that is for translation of one language site. We have multilingual site with two languages. After that update we loose transaltions of one language we made. 

We use qtransalate-XT plugin for translating strings, but when we enter phrase like[:en]Property[:hr]Nekretnina[:] it is good for a few days and after few days we loose one langauage. 

We try and {:} and enter class name in admin of custom fields but do not work. Can help?

Thanx Zeljko

![image](https://user-images.githubusercontent.com/54800537/83977012-0eb31b80-a8fe-11ea-860e-78608044a3cb.png)

**Comment by herrvigg** [comment] 2020-09-26 11:19
Sorry but I don't really understand why you lose the values "after a few days"... either it is translated or not.

Did you really enable the translation with a i18n-config json file or with hooks? It doesn't seems so. Please take a look at the: https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide.

If the values change you have some other part of code overwriting the values, but in that case i don't know where to look with so little information. You may find some tips to debug in https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting.

I close this ticket for now, the problem is not identified well enough.

**Closed by herrvigg** 2020-09-26 11:19 UTC
Labels: integration
