### ISSUE TITLE
slugs forgotten

### ISSUE THREAD

**Issue by vonsch76** [qtranslate/qtranslate-xt#1275] opened 2023-01-06 15:44 UTC
Seems that there is a problem with the slugs module in 3.13.0
After a day the slugs set are simply forgotten, disappear even from the DB. Both the first and second language slugs disappear, no error message goes with that.
Had no issues with earlier versions.

**Comment by herrvigg** [comment] 2023-01-08 12:01
In 3.13.0 I only made a minor change in Slugs about initialization sequence. I don't think it can explain this. IMO if there's a real problem it's not due to 3.13.0.

> After a day the slugs set are simply forgotten

They are stored in the post meta. If you don't update the post there's no reason why qTranslate would delete them.

**Comment by herrvigg** [comment] 2023-01-08 12:11
I would rather look at other plugins to find an explanation. Is there any other you could think of?

**Comment by vonsch76** [comment] 2023-01-08 13:13
The only plugin I upgraded was the qtranslate-xt, that is why I suspect it to be the problem.

**Comment by herrvigg** [comment] 2023-01-09 22:40
I'm getting a bit lost with the discussion in the other thread.
If there's still a problem of data being erased, do you have possibility to do some experiments? We could try from 3.13.0 and restore the slugs code from 3.12.1 though I don't think this explains the problem.

**Comment by vonsch76** [comment] 2023-01-10 06:33
The other thread is partly unlreated. SasaHref01 just found a friendly face.
I am happy to do the experment, but how can we log it. I already had the data loss twice, then went back to the earlier and that works without data loss.

**Comment by herrvigg** [comment] 2023-01-15 11:59
You could try taking 3.13.0 and revert the change in slugs, there's only one commit: https://github.com/qtranslate/qtranslate-xt/commit/e13fa39945f1c1abc409fa2e0dbe1e7eac872ca5.
If you have git you could use `git revert` but it's also easy to do by hand.
The first change in `module/slugs/qtx_module_slugs`. should not matter at all, if that code is run, the module has to be active.
The change in `module/slugs/slugs.php` below the includes.
```
# 3.13.0
if ( is_admin() ) {
    include_once( dirname( __FILE__ ) . '/admin/slugs-admin.php' );
}

add_filter( 'qtranslate_convert_url', 'qtranxf_slugs_convert_url', 10, 2 );

global $qtranslate_slugs;
$qtranslate_slugs = new QTX_Module_Slugs();
$qtranslate_slugs->init();
```
Revert that to
```
# 3.12.1
global $qtranslate_slugs;
$qtranslate_slugs = new QTX_Module_Slugs();

if ( is_admin() ) {
    include_once( dirname( __FILE__ ) . '/admin/slugs-admin.php' );
}

add_action( 'plugins_loaded', array( $qtranslate_slugs, 'init' ) );
add_filter( 'qtranslate_convert_url', 'qtranxf_slugs_convert_url', 10, 2 );
```

**Comment by herrvigg** [comment] 2023-01-15 12:02
The goal is to narrow it down.
I don't think it's the reason, the problem could be there already in 3.12.1 more or less hidden.
But if this revert works with the 3.13.0 baseline it would be surprising.

**Comment by vonsch76** [comment] 2023-01-15 16:22
I also don't believe that it is something that existed earlier. Maybe some interaction between php 7.4, wp 5.7.7, but now moved to php 8.1 and wp 6.0. Testing, nothing so far - but only half a day passed.

**Comment by herrvigg** [comment] 2023-01-15 18:22
> I also don't believe that it is something that existed earlier. 

I don't think there's a regression in 3.13.0. The `plugins_loaded` hook is legacy code from the time Slugs was a plugin. The modules don't need this even and should not use it. Each module entry point is called in QTX `qtranxf_init_language` which itself is already a callback for `plugins_loaded`. The only potential problem here is the order in which other components are loaded.

> Testing, nothing so far - but only half a day passed.

Testing which QTX version or which changes?

**Comment by vonsch76** [comment] 2023-01-16 07:33
The newest QTX, 3.13.0. Still nothing, but let's give it another 2-3 days.

**Comment by vonsch76** [comment] 2023-01-18 07:29
@herrvigg everything seems to work fine, no unexpected events. The good part is that qtx is solid, thanks to you for that. The bad part is that I have no clue what caused the issue earlier. Anyway I believe you can close this ticket.

**Comment by fintinc** [comment] 2023-01-20 08:33
Same problem here!
After the update all slugs in posts, tags and categories in wp editor are empty... they reappear after updating the post.
they still seem to work in the frontend but some languages are messed up. e.g. some french tags now appear between german tags.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/19888073/213650956-96c454a8-d8b1-4a22-ba16-26a21ce8dbbd.png">
![image001](https://user-images.githubusercontent.com/19888073/213651117-5cdbab2d-5b00-4c83-8eae-c2f960d0d541.png)

**Comment by vonsch76** [comment] 2023-01-20 08:51
@fintinc can you specify the WP and QTX versions you have? Maybe connected.

**Comment by fintinc** [comment] 2023-01-20 10:59
@vonsch76 WordPress 6.1.1 and it happend after updating to QTX 3.13.0

**Comment by vonsch76** [comment] 2023-01-20 11:11
Try to go back to WP 6.0, the Metaslider issue also seems to be on WP 6.1.

**Comment by herrvigg** [comment] 2023-03-12 20:31
> After the update all slugs in posts, tags and categories in wp editor are empty... they reappear after updating the post.
Maybe there's something we missed, but if it sorted out by updated it becomes a minor problem.

> they still seem to work in the frontend but some languages are messed up. e.g. some french tags now appear between german tags.
Is it still the case? Did you try with WP 6.0?

**Comment by herrvigg** [comment] 2023-04-13 07:18
No update for 1 month, I close this ticket.

**Closed by herrvigg** 2023-04-13 07:18 UTC
Labels: need info, module: slugs
