### ISSUE TITLE
[WC] Product variations not show in product page

### ISSUE THREAD

**Issue by cyberneco** [qtranslate/qtranslate-xt#752] opened 2019-10-29 14:51 UTC
Hi!

Congratulations for the project.

I'm creating a online store with Q Translate XT and Impreza Theme.

When i create a simple product all run correctly, but when i create a variable product, in the page of this, the dropdown list don't show the variations.

If i desactivate the Qtranslate plugin, it shows correctly.

An example: [](https://dev.sitenrain.ch/en/product/palmeri-navalta/)

I attach the report of the plugin.

Anybody can help me? 

Many thanks

[Report.txt](https://github.com/qtranslate/qtranslate-xt/files/3784133/Report.txt)

**Comment by cyberneco** [comment] 2019-10-29 21:08
For discarding some things: no is for CSS 

![photo_2019-10-29_22-06-22](https://user-images.githubusercontent.com/57144101/67809104-6223d800-fa98-11e9-8525-eab38ecfba4d.jpg)

**Comment by herrvigg** [comment] 2019-10-31 10:17
See also #612 #645

**Comment by cyberneco** [comment] 2019-10-31 11:29
Solved. I have installed the 3.5.5 version of Qtranslate-XT and 1.3 version of Woocommerce-Qtranslate.

Many thanks.

**Comment by herrvigg** [comment] 2019-10-31 11:47
It doesn't work with qT-XT 3.7.1? This is not solved in that case. These old versions are not going to be maintained and the more it goes the more you will have many other issues.

**Comment by herrvigg** [comment] 2019-10-31 19:19
Yes this error message is not very friendly, but the reason is that plugin is obsolete since qT-XT 3.6.0, there is now a specific module for that so you can't enable the old plugin later (to avoid the name conflicts more refactoring is needed). The module was created from the latest of this plugin and there's almost no specific change for WC since then (see release notes), so you should have find yourself in the same situation as before, plus all the fixes for qT-XT.

**Comment by cyberneco** [comment] 2019-10-31 19:28
> 
> 
> Yes this error message is not very friendly, but the reason is that plugin is obsolete since qT-XT 3.6.0, there is now a specific module for that so you can't enable the old plugin later (to avoid the name conflicts more refactoring is needed). The module was created from the latest version of this plugin and there's almost no specific change for WC since then (see release notes). So with the latest version (3.7.1), but without the obsolete plugin, you should find yourself in the same situation as before, plus all the fixes for qT-XT.

Ok. But, a solution for my problem is possible? Because i don't understand well the cause.

I have read the post #612 and #645 but i don't conclude anything

**Comment by herrvigg** [comment] 2019-10-31 19:47
I don't use WC so it's a bit difficult for me to understand what is going on. First, i noticed you were using the old plugin 1.3 and not 1.4 which is supposed to be the latest version. But 1.4 was never uploaded to WordPress if i remember well.

To be sure, if you have the possibility and the will to test, you could fallback to qT-XT 3.5.5 and try 1.4 from github to see if you have the same problem?

In that case, it would be a bug introduced between those two versions (1.3 vs 1.4). This is quite surprising, since 1.4 was actually supposed to fix a bug related to those variable products, as described in #277, but maybe it broke something else at the same time. From the diff in github on the legacy plugin it should be possible to understand what could cause the possible regression, though we should keep the possible fixes at the same time...

Maybe @wywarren could have some better clue of the changes behind this? I know he was doing some tests some time ago.

**Comment by cyberneco** [comment] 2019-10-31 19:54
Yes, i have the same problem. It's tested.

With the 1.3 version activated only shows the sencond language variations. The main language doesn't show it.

**Comment by cyberneco** [comment] 2019-10-31 20:05
I've desactivated 1.3 and 1.4 versions, and i am only using the QTranslat XT 3.5.5  and the problem dissapears. BUFF

**Comment by herrvigg** [comment] 2019-10-31 22:17
Sorry but i'm not following anymore.
If you use XT 3.5.5 then you should enable the old legacy plugin for WC, otherwise you won't have the translation functionalities specifically for WC. You will have just generic functionalities.

Can you re-assume the differences between:
a- XT 3.5.5 and legacy plugin 1.3
b- XT 3.5.5 and legacy plugin 1.4
c- XT 3.7.1 alone (anyway incompatible with legacy plugin)

Other configurations should not be relevant. From my point of view, at least b and c should be the same because the code for WC is roughly the same.

**Comment by cyberneco** [comment] 2019-10-31 22:24
Ok. I will try explain better

If i use XT 3.5.5 with legacy plugin 1.3 or 1.4, the variable dropdown list doesn't show.
If i use XT 3.7.1 alone,  the variable dropdown list doesn't show.
If i use XT 3.5.5 alone, without legacy plugin, installing the modules apart, all run ok and the products, in the variable dropdown list appear correctly.

**Comment by herrvigg** [comment] 2019-10-31 22:32
OK got it except for "installing the modules apart" --> ??

However in all the 3 first cases, if you don't have the specific plugin/module for WC you are missing all the specific functionalities of translation for the WC elements, so you should see some missing parts.

This said, if you can live with it, it's fine but in that case it would be better to for you to still use the latest 3.7.1 (and next versions to come) but only disable the WC module that is apparently creating problems for you. The easiest way is simply to rename manually the folder called `qtranslate-xt/modules/woo-commerce` to anything else, but that's just a temporary solution. At some point we should have an option to do that from the plugin settings.

**Comment by cyberneco** [comment] 2019-10-31 23:01
Ok, i have followed your instructions and yes. Now all ok.

I'll wait for next versions and let's see if the issue is solved.

Many thanks for your help, really.

Regards

**Comment by alezzzzz** [comment] 2019-12-05 16:24
Running into the same problem - as I don't need to translate variations instead or renaming module/**woo-commerce**  I just added this to my function.php :

> remove_filter( 'woocommerce_product_get_attributes', 'qwc_product_get_attributes', 5 );

This way I don't get the error, variations show and the product title and description gets translated in front end.

**Comment by herrvigg** [comment] 2020-02-29 14:41
@cyberneco @alezzzzz also here, could you try with PR #790 to see if it fixes this problem?

**Comment by herrvigg** [comment] 2020-03-10 19:43
Fixed in [3.7.3]( https://github.com/qtranslate/qtranslate-xt/releases/tag/3.7.3)

**Closed by herrvigg** 2020-03-10 19:43 UTC
Labels: integration
