### ISSUE TITLE
Custom menu with #?lang=xx ignores URL link

### ISSUE THREAD

**Issue by cajucosta** [qtranslate/qtranslate-xt#999] opened 2021-04-07 06:27 UTC
Hello, thanks for keeping this amazing plugin running!
I'm trying to redirect to a Custom menu link in a specific language, like the example on your FAQ:

mysite.com/about-us#?lang=en should redirect to mysite.com/en/about-us 
Instead, it redirects to mysite.com/en.

It defines the language but ignores the complete URL

**Comment by topaz-rep** [comment] 2021-04-07 07:46
Try this: mysite.com/about-us?lang=en

**Comment by cajucosta** [comment] 2021-04-07 08:43
This redirects me to the right page, but doesn't change language:
Redirects to: mysite.com/about-us
Instead of: mysite.com/en/about-us

**Comment by herrvigg** [comment] 2021-04-07 10:57
It seems you are mixing query mode (?lang) with pre-path mode (/en). You should decide for one mode and stick to it. I recommend the default pre-path mode. The query mode is more difficult to manage and there may be some bugs.

**Comment by cajucosta** [comment] 2021-04-07 11:49
Thanks for the reply.
Ok so, since I'm using Pre path Mode, how can I achieve this?
https://github.com/qtranslate/qtranslate-xt/wiki/Front-language-switching#how-can-i-make-url-of-a-custom-menu-item-to-be-always-converted-to-a-specific-language

**Comment by herrvigg** [comment] 2021-04-07 12:11
The example was for a query string mode, I should update it with the default pre-path mode instead. In your menu just put a link to `/en/your-menu-url/`. You don't even need to prefix with the website, with HTTP it's the current one by default.

This kind of link is when you want to **force** a language switch. But for regular menus you normally don't specify the language,  you'd just have `/your-menu-url` and qTranslate takes care of the active language from the cookie.

To switch language you'd rather have a separate [Language Switcher Menu](https://github.com/qtranslate/qtranslate-xt/wiki/Front-language-switching#language-switcher-menu) but you can also come up with your own custom menu for the same purpose.

**Comment by cajucosta** [comment] 2021-04-07 12:19
I've tried that, it simply removes the /en/ from the link, 

![image](https://user-images.githubusercontent.com/82079555/113865070-f7f28500-97ab-11eb-952a-ce06dcd659e6.png)
![image](https://user-images.githubusercontent.com/82079555/113865153-0f317280-97ac-11eb-89a2-f2fbbbb03679.png)
![image](https://user-images.githubusercontent.com/82079555/113865190-19ec0780-97ac-11eb-9c4d-118c54ee0bbc.png)

**Comment by herrvigg** [comment] 2021-04-07 12:38
Do you have English as default language? Do you have "hide default language" checked? In that case it's normal.

**Comment by herrvigg** [comment] 2021-04-07 12:41
> it simply removes the /en/ from the link,

You mean your target URL is without `/en/`? The menu link should remain as you save it.

**Comment by cajucosta** [comment] 2021-04-07 12:44
Default language is Portuguese (pb), but I want that, whan user clicks on this link, he should arrive on that page in English, but for some reason, even putting the /en/ on the Menu link...on the site, it disappears.

**Comment by herrvigg** [comment] 2021-04-07 12:48
Do you mean it your redirected target does not contain `/en/` ? When you save the menu do you still have the `/en/` in the link?

The problem of redirection could be due to this `/ativy2/` prefix. In your general settings what do you have as WordPress URL and Site Address URL?

**Comment by cajucosta** [comment] 2021-04-07 12:52
Exactly, 
Add this link on the menu: /ativy2/en/home-en (complete would be this: https://cajucosta.com/ativy2/)
Save it (yes, on Menu structure the /ativy2/en/home-en is still there)
Go the home page > Refresh it
menu shows this link: https://cajucosta.com/ativy2/home-en/ (with contents in Portuguese)

WP and Site URL both: https://cajucosta.com/ativy2

**Comment by herrvigg** [comment] 2021-04-07 12:55
Can you go in the qTranslate settings / Troubleshooting / Collect information and copy your configuration here?

**Comment by cajucosta** [comment] 2021-04-07 12:55
Sure one sec

**Comment by cajucosta** [comment] 2021-04-07 12:56
Version:
{
  "PHP_VERSION": "7.4.16",
  "WP_VERSION": "5.7",
  "QTX_VERSION": "3.9.3",
  "Plugins": [
    "AddToAny Share Buttons 1.7.44",
    "All-in-One WP Migration 7.40",
    "Classic Editor 1.6",
    "Elementor 3.1.4",
    "Font Awesome 4.0.0-rc21",
    "GitHub Updater 9.9.10.4",
    "Elementor - Header, Footer &amp; Blocks 1.5.8",
    "MetaSlider 3.20.3",
    "Popup Maker 1.16.1",
    "Post Carousel for DV Builder 1.3",
    "Smart Post Show (formerly Post Carousel) 2.2.7",
    "Post Duplicator 2.22",
    "qTranslate-XT 3.9.3",
    "Shortcodes Ultimate 5.9.8",
    "WP-PageNavi 2.93.4"
  ]
}

Configuration:
{
  "default_language": "pb",
  "enabled_languages": [
    "en",
    "pb",
    "es"
  ],
  "flag_location": "plugins/qtranslate-xt-3.9.3/flags/",
  "language_name": {
    "en": "EN",
    "pb": "PT",
    "es": "ES"
  },
  "locale": {
    "en": "en_US",
    "pb": "pt_BR",
    "es": "es_ES"
  },
  "locale_html": {
    "en": "",
    "pb": "",
    "es": ""
  },
  "not_available": {
    "en": "Sorry, this entry is only available in %LANG:, : and %.",
    "pb": "Desculpe-nos, mas este texto está apenas disponível em %LANG:, : y %.",
    "es": "Disculpa, pero esta entrada está disponible sólo en %LANG:, : y %."
  },
  "date_format": {
    "en": "%A %B %e%q, %Y",
    "pb": "%d \\d\\e %B \\d\\e %Y",
    "es": "%d \\d\\e %B \\d\\e %Y"
  },
  "time_format": {
    "en": "%I:%M %p",
    "pb": "%H:%M hrs.",
    "es": "%H:%M hrs."
  },
  "flag": {
    "en": "gb.png",
    "pb": "br.png",
    "es": "es.png"
  },
  "url_mode": 2,
  "use_strftime": 3,
  "filter_options_mode": 0,
  "language_name_case": 0,
  "detect_browser_language": false,
  "hide_untranslated": false,
  "show_displayed_language_prefix": false,
  "show_alternative_content": true,
  "hide_default_language": true,
  "use_secure_cookie": false,
  "header_css_on": true,
  "header_css": ".qtranxs_flag_en {background-image: url(https://cajucosta.com/ativy2/wp-content/plugins/qtranslate-xt-3.9.3/flags/gb.png); background-repeat: no-repeat;}\n.qtranxs_flag_pb {background-image: url(https://cajucosta.com/ativy2/wp-content/plugins/qtranslate-xt-3.9.3/flags/br.png); background-repeat: no-repeat;}\n.qtranxs_flag_es {background-image: url(https://cajucosta.com/ativy2/wp-content/plugins/qtranslate-xt-3.9.3/flags/es.png); background-repeat: no-repeat;}\n",
  "text_field_filters": [],
  "term_name": [],
  "disable_client_cookies": false,
  "ignore_file_types": [
    "gif",
    "jpg",
    "jpeg",
    "png",
    "svg",
    "pdf",
    "swf",
    "tif",
    "rar",
    "zip",
    "7z",
    "mpg",
    "divx",
    "mpeg",
    "avi",
    "css",
    "js",
    "mp3",
    "mp4",
    "apk"
  ],
  "url_info": {
    "cookie_lang_front": "pb",
    "cookie_lang_admin": "pb",
    "cookie_front_or_admin_found": true,
    "scheme": "https",
    "host": "cajucosta.com",
    "path": "/ativy2/wp-admin/admin-ajax.php",
    "query": "action=admin_debug_info",
    "path-base": "/ativy2",
    "wp-path": "/wp-admin/admin-ajax.php",
    "language_neutral_path": true,
    "http_referer": "https://cajucosta.com/ativy2/wp-admin/options-general.php?page=qtranslate-xt",
    "referer_admin": true,
    "doing_front_end": false,
    "lang_cookie_admin": "pb",
    "lang_admin": "pb",
    "language": "pb",
    "set_cookie": false,
    "page_referer": "options-general.php"
  },
  "language": "pb",
  "editor_mode": "1",
  "highlight_mode": 1,
  "auto_update_mo": true,
  "hide_lsb_copy_content": false,
  "lsb_style": "Simple_Buttons.css",
  "config_files": [
    "./i18n-config.json"
  ],
  "custom_i18n_config": [],
  "custom_fields": [],
  "custom_field_classes": [],
  "post_type_excluded": [],
  "translator": {},
  "qtrans_compatibility": false
}

Browser:
{
  "cookies": [],
  "navigator": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36"
}

**Comment by herrvigg** [comment] 2021-04-07 13:26
I don't see any problem so far. You have the cookies and "path-base" is correct with `ativy2`.
Just as a test could you try to disable "hide_default_language" (below URL mode)? This should only affect the default but maybe there's another bug.

> menu shows this link: https://cajucosta.com/ativy2/home-en/ (with contents in Portuguese)

Maybe we have something there. Do you mean it shows this link when you hover the menu? In that case the problem is before the redirection.

**Comment by cajucosta** [comment] 2021-04-07 13:31
Yes, it shows me this link when I hover the menu

I disabled the hide default language:
I save the menu link like this: /ativy2/en/home-en
On hover on the menu looks like this: https://cajucosta.com/ativy2/pb/home-en/

**Comment by cajucosta** [comment] 2021-04-07 13:33
You can see it for yourself here (top menu, TEST link): https://cajucosta.com/ativy2/pb/
And this is how it looks on my admin:
![image](https://user-images.githubusercontent.com/82079555/113874983-9b489780-97b6-11eb-9717-ccd9faf8c565.png)

**Comment by herrvigg** [comment] 2021-04-07 13:35
Mmm so it seems there's a bug indeed! Probably something with the path-base (here `abity2`) not working well.
Maybe as a first try, save the link as `/en/home-en`.

Also, if you have the possibility to try without `abity2` in your Site/WP URL that should certainly work but this could require more changes in your WP setup. qTranslate should work with this but there might be a bug here.

**Comment by cajucosta** [comment] 2021-04-07 13:39
Well, this site is on development, it's installed under https://cajucosta.com/ativy2, because https://cajucosta.com is another site... let me check if I can try test this there.

**Comment by cajucosta** [comment] 2021-04-07 13:47
ok, so I tested this on other site
Home url: https://katmee.com/pb/
The link I set umpon the menu: /en/about/
The link I got on hover: https://katmee.com/pb/about/

**Comment by cajucosta** [comment] 2021-04-07 13:50
I switched to query mode
Site url: https://katmee.com/?lang=pb
Menu link: /about?lang=en
The link I got on hover: https://katmee.com/about?lang=pb

**Comment by herrvigg** [comment] 2021-04-07 16:57
Thanks for testing, in fact it's not related to the site URL prefix and I can reproduce it! Definitely a bug.
I have to look better, I'll keep you updated.

**Comment by cajucosta** [comment] 2021-04-07 18:35
Dude you're awesome, thank you so much!

**Comment by herrvigg** [comment] 2021-04-09 13:21
I've searched a bit in the existing issues and found a solution, it's in the Wiki:
https://github.com/qtranslate/qtranslate-xt/wiki/Front-language-switching#how-can-i-prevent-url-of-a-custom-menu-item-from-being-converted
To prevent the transformation of the link just add `?setlang=no` to your link. I'm not really happy with that solution but this is how it's working right now. That should solve your case for example with ` /en/about/?setlang=no`.

However there are a few other problems in `qtranxf_wp_get_nav_menu_items`.

https://github.com/qtranslate/qtranslate-xt/wiki/Front-language-switching#how-can-i-make-url-of-a-custom-menu-item-to-be-always-converted-to-a-specific-language
In fact `#?lang=xx` is hard-coded and it's ignoring the current URL mode. Worse, it's breaking the given link by always redirecting to the home URL. So that would be the issue you raised, at least this part should be fixed.

Beside this, there are some questions about the translations of these custom menus: https://github.com/qtranslate/qtranslate-xt/issues/599
I still don't really understand the whole logic with the legacy functionalities. But this might be a different topic.

**Comment by cajucosta** [comment] 2021-04-11 05:38
Hello, thanks for the reply, but that's actually the opposite of what I want to do:
I don't want the prevent the custom URL to be translated, I want it to be always translated to the a specific language.

**Comment by cajucosta** [comment] 2021-04-11 05:46
I've tested and worked!
Sorry for the previous response, I've made a mistake on the testing! 

So the final custom link looks like this:
/en/about/?setlang=no
And voilá, works!

Thanks again and have a great weekend!

**Closed** 2021-04-11 05:47 UTC
Labels: bug, core
