### ISSUE TITLE
E_Error after WP5.3 Update

### ISSUE THREAD

**Issue by cyberfly999** [qtranslate/qtranslate-xt#764] opened 2019-11-25 16:45 UTC
Hi,

After updating WP to 5.3 I got the following E_Error and JS-Error. It may be related to #759. ACF-PRO is 5.7.10.

EDIT: Must be related to ACF PRO. If I run WP only with ACF PRO, the Errors still occur.

Thanks!

#WordPress-Version&nbsp;5.3
Aktuelles Plugin: qTranslate-XT (Version 3.7.1)
PHP-Version&nbsp;7.2.24###

#

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 86 der Datei /home/proitera/public_html/productive_wp/wp-content/plugins/qtranslate-xt-3.7.1/modules/acf/src/acf_5/fields/text.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined function acf_esc_attrs() in /home/proitera/public_html/productive_wp/wp-content/plugins/qtranslate-xt-3.7.1/modules/acf/src/acf_5/fields/text.php:86
Stack trace:
#0 /home/proitera/public_html/productive_wp/wp-includes/class-wp-hook.php(288): acf_qtranslate_acf_5_text->render_field(Array)
#1 /home/proitera/public_html/productive_wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /home/proitera/public_html/productive_wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/proitera/public_html/productive_wp/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-field.php(433): do_action('acf/render_fiel...', Array)
#4 /home/proitera/public_html/productive_wp/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-field.php(584): acf_render_field(Array)
#5 /home/proitera/public_html/productive_wp/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-field.php(390): acf_render_field_wrap(Array, 'div', 'label')
#6 /home/pr####

<img width="741" alt="screen" src="https://user-images.githubusercontent.com/8487629/69559899-1b4bd400-0fab-11ea-9d23-bf6145e7c653.png">

**Comment by herrvigg** [comment] 2019-12-01 15:17
I can't reproduce the problem with ACF free. Did you try the trick that @hirasso gave in #759? Maybe we can find a better fix.

**Comment by hirasso** [comment] 2019-12-06 12:44
Hi there, I only get this error on my frontend, but the OP doesn't mention anything about that.

**Comment by herrvigg** [comment] 2019-12-08 23:01
But `acf_form` is only used on the admin side no? By front-end in qTX we mean the final rendering of the page for regular users by contrast to the admin section.

Nevertheless it sounds like the same problem. Can you check in which order the JS scripts are loaded? Try to put ACF **after** qTX.

**Comment by hirasso** [comment] 2019-12-09 10:31
@herrvigg , `acf_form()` is for embedding a ACF Field Group in the frontend. Have a look at the documentation: https://www.advancedcustomfields.com/resources/acf_form/

**Comment by herrvigg** [comment] 2020-02-18 12:56
I managed to reproduce it, it's rather due to `acf_form_head` which enables the loading of the client scripts but there's definitely something wrong with the order. To me it looks exactly as #759 so i close this one. Just surprised this was appearing after a WP update, still i don't the see the relation but in any case it should be fixed.

**Closed by herrvigg** 2020-02-18 12:56 UTC
