### ISSUE TITLE
Notification through GitHub Updater: You have version 3.7.3 installed. Update to 3.8.0.dev.6.

### ISSUE THREAD

**Issue by BjoernKW** [qtranslate/qtranslate-xt#814] opened 2020-04-06 12:40 UTC
I'm currently seeing this message under "WordPress Updates":

"You have version 3.7.3 installed. Update to 3.8.0.dev.6."

I suppose this isn't intentional because 3.7.3 is listed as the  latest 
qTranslate-XT release and 3.8.0.dev.6 presumably is a dev-only version not intended for a production website.

**Comment by herrvigg** [comment] 2020-04-07 08:56
I just merged the gutenberg branch in master so you get that update as a pre-release with GitHub updater. I could have named it 3.8.0.beta.1 or 3.8.0.rc.1 but it's only a subjective matter of naming. I don't expect many changes until 3.8.0 because some have tested it quite a lot in the previous branch. In any case there are some limitations with gutenberg, the question is more about having the main functionality to work with gutenberg without regressions on the rest. Nothing forces you to update, but the more people test it the better it is.

**Comment by dlambova** [comment] 2020-04-07 09:17
There is an issue with the update: when I click on the button to update the plugin it tells me it has been updated successfully but again I see the same update notification and the version remains 3.7.3. This has been going on for the last three days. Is it possible to be an issue with the Git Hub updater plugin? Today it failed the last update, even though I tried two times. 
Thanks

**Comment by reddo** [comment] 2020-04-07 10:04
> There is an issue with the update: when I click on the button to update the plugin it tells me it has been updated successfully but again I see the same update notification and the version remains 3.7.3. This has been going on for the last three days. Is it possible to be an issue with the Git Hub updater plugin? Today it failed the last update, even though I tried two times.
> Thanks

The same's happening to me too.

**Comment by herrvigg** [comment] 2020-04-07 10:54
Ah yes that's right, it's because Github updater wants a matching git tag when it's on the master branch. At this point better to release it completely with a full version. Coming now.

**Comment by herrvigg** [comment] 2020-04-07 11:31
Version 3.8.0 now released! 

New feature! Initial support of Gutenberg, with some limitations. Read carefully our [Gutenberg FAQ](https://github.com/qtranslate/qtranslate-xt/wiki/FAQ#gutenberg) before use.

**Closed** 2020-04-07 11:31 UTC
Labels: gutenberg
