### ISSUE TITLE
LSB button (flags) not display

### ISSUE THREAD

**Issue by renad** [qtranslate/qtranslate-xt#650] opened 2019-03-09 16:28 UTC
Hi,
LSB button is not visible on pages, posts, product ... LSB buttons are only visible for widgets.
see attachments ...

I use latest WP v5.1
I tested it with different themes in different PHP settings (PHP 7.1, PHP 7.2, PHP 7.3)
I tested with Visual Composer v5.6 and v5.7

Note: with old qTranslate-X work it fine ...
Help me, please ...

![1](https://user-images.githubusercontent.com/1554402/54074261-b28fc080-4290-11e9-8637-af0a83713100.jpg)
![2](https://user-images.githubusercontent.com/1554402/54074263-b7547480-4290-11e9-926c-855b35b58e7b.jpg)

**Comment by herrvigg** [comment] 2019-03-09 23:36
What is the difference between these two images? Is the first one qT-X and the other one qT-XT?

Not working in post/page but works for widgets? It seems to work for most of people so there's a specific problem with JS or integration issues. The funny thing is also there's another ticket where it doesn't work for the widgets... https://github.com/qtranslate/qtranslate-xt/issues/616

Do you have errors in the browser console?

**Comment by renad** [comment] 2019-03-10 10:49
Yes,  the first image is qT-X and the second image qT-XT ...

Here is link:
https://test.renad.sk/wp-admin/
testing
testing@qTranslate-XT

**Comment by herrvigg** [comment] 2019-03-10 11:24
OK thanks, now i see. The problem is that you have a script `qtranslatex-backend.js` that is loaded before `qtranslate-xt/js/common.js` so it if fails here :

```
(function ( $ ) {
	$( function () {
		var Manager = qTranslateConfig.js.get_qtx(); // <-- not loaded yet!
```
Where does this  `qtranslatex-backend.js` come from btw? It looks like a third-party script from composer but not something that was written by the qTranslate authors. Still i don't see why it works with qT-X and not qT-XT. I released in 3.5.2 some refactoring with the jQuery handler also due to deprecated functions but it was supposed to be without effect and it seems to work well for the majority of people. Here we need to clarify how the loading sequence is supposed to work.

**Comment by herrvigg** [comment] 2019-03-10 12:00
Mmmm i think i got something with how this `qTranslateConfig.js.get_qtx` was declared. It was actually done earlier as a global declaration when the script was loaded and not in the jQuery handler so that certainly explains how it could work before. I'll try find a fix for that. But i really hate how this integration is done, we need to move to modern JS code...

**Comment by renad** [comment] 2019-03-10 12:25
For now, thank you very much !!!

**Comment by herrvigg** [comment] 2019-03-10 12:29
By integration i didn't mean just the code of your project but all the interface provided by qTranslate. Imo it should be completely refactored with a npm package.

For now do you have the possibility to test a fix on a separate branch with git? Better if we can validate it separately before merging into master.

**Comment by renad** [comment] 2019-03-10 17:25
The link I provided is a testing page and we can test it there.

**Comment by herrvigg** [comment] 2019-03-10 18:23
You can try with this branch: [fix/js-get-qtx](https://github.com/qtranslate/qtranslate-xt/tree/fix/js-get-qtx).
Just do `git fetch && git checkout fix/js-get-qtx`.

Note: better set `WP_DEBUG`  to true here so it will load the non-minified version without troubles with the browser cache. Otherwise you need to create a fake QTX_VERSION just for test.

**Comment by renad** [comment] 2019-03-10 19:15
For me it would be simpler if you could give me a download link of the test version of qTranslate-XT plugin, as I don't work with git.

**Comment by renad** [comment] 2019-03-10 19:19
Right now I'm going to develop two-language sites with woo commerce e-shop with two currencies so I can test the plugin even on more complicated issues as dual languages.

**Comment by herrvigg** [comment] 2019-03-10 19:42
I can't create a release for every commit so you need to take every patch separately. There's only 1 JS file changed, but its also exists as minified. You just need to replace those in your repo (in qtranslate-xt/admin/js).

Debug version (recommended - but you need `WP_DEBUG=true` in your `wp-config.php`)
https://github.com/qtranslate/qtranslate-xt/blob/fix/js-get-qtx/admin/js/common.js

Minified (`WP_DEBUG=false` and you need to patch QTX_VERSION locally)
https://github.com/qtranslate/qtranslate-xt/blob/fix/js-get-qtx/admin/js/common.min.js

**Comment by herrvigg** [comment] 2019-03-10 19:47
Alternatively you could still download the ZIP of the whole branch: https://github.com/qtranslate/qtranslate-xt/archive/fix/js-get-qtx.zip

(just rename your original qtranslate-xt before unzipping)

**Comment by renad** [comment] 2019-03-10 20:02
Unfortunately the flags are still not visible even after uploading this version on the server.
Instead a problem with the plugin qTranslate slug has appeared.
see – https://test.renad.sk

You can directly use my test web for further code changes. GEO IP is off.

**Comment by herrvigg** [comment] 2019-03-10 21:11
That's weird, the flags work for me now. I suppose you have a cached version loading the old script. It's because you run with the minified versions, as said you should put `define('WP_DEBUG', true)` in your `wp-config.php` or patch QTX_VERSION but i highly recommend the first option. However i don't see the problem with the qTranslate slug and i don't understand why you would have some changes if you run with the previous version.

**Comment by renad** [comment] 2019-03-10 21:22
Yes we have used the first version.
The flags are working now - I forgot to refresh the page :-)

The problems with qTranslate slug are persisting. Please see the attachment.
![Safari](https://user-images.githubusercontent.com/1554402/54091669-f4992f00-4382-11e9-8850-e65276e5d329.jpg)

**Comment by herrvigg** [comment] 2019-03-10 21:27
OK good!
The problem here is something else in qTranslate-slug, it's (still) an independent plugin that i don't have control on. You didn't see this error before because the script failed earlier. If you switch to qTranslate-X you will see the same. So i'd say the fix works fine!
This remaining problem is a very minor thing that should be easy to solve i n qTranslate-slug.

**Comment by renad** [comment] 2019-03-10 21:41
Yes, it's like that ..
after switching to qTranslate-X, the error message "qTranslate slug" still appears ...
:-(

**Comment by herrvigg** [comment] 2019-03-10 21:51
It's actually a good notice, you have a new PHP version telling exactly what should be fixed in the code, there's probably a way to disable these PHP notices for the users and this should be easy for qtranslate-slug don't worry :)

I will merge the fix soon in qT-XT so this issue can be closed. 

Btw it seems you are still running with the minified versions (it's loading common.min.js and not common.js). But you managed to load the patched version somehow so that's ok. Nice site also :)

**Closed by herrvigg** 2019-03-10 21:51 UTC
Labels: integration
