### ISSUE TITLE
Qtranslate-xt generates errors to other plugins

### ISSUE THREAD

**Issue by sviluppomania** [qtranslate/qtranslate-xt#701] opened 2019-06-11 14:59 UTC
Hello,
I find that qtranslate-xt creates problems with other plugins and don't tell me otherwise. If I turn off qtranslate all the problems disappear.

**Plugins list:**

**1a)** Advanced Ads;
**2a)** Wordpress Social Login

**Respective problems:**

**1b)** Being a plugin that connects to various advertising accounts like AdSense generates an Ads.txt file which is essential to report advertising accounts but, with active qtranslate-xt finds this error: 

> The ads.txt file cannot be inserted because the URL contains a subdirectory. You need to make the file available on https://www.xxxx.xxx;

**2b)** This plugin serves as the name for the Social Login, in the diagnostics it presents this error: 

> Check for WordPress directories functions.
> 
> plugins_url () is not returning an expected result: https://www.xxxx.xxx/wp-content/plugins

Similar to the first, it evidently generates a redirect of the URLs.

There is a solution? Do you have ideas about this?

You have a lot of information to solve these problems.
The other Plugins that generate an error are not, but it is qtranslate-xt that generates them...

**Comment by herrvigg** [comment] 2019-06-12 10:25
Sorry but i need more technical info to understand what's behind this, especially when it's about integration with other plugins. The WP architecture and the design of qTranslate can lead to very complex issues. Understand i don't know how every single plugin works. To come up with some fixes for very specific cases a more in-depth analysis is needed before hand. As a developer and user you should be able to push the investigation further on your side to tell which part in qTranslate-XT might be problematic.

1. Advanced Ads
How is the file generated? I don't use this plugin but i have a site working with AdSense and ads.txt. This file can be put manually and it works fine with qTranslate-XT. So the problem depends on how the file is generated by this plugin when combined with qTranslate. I could also be a problem in how the file is read by the plugin but i think the problem is rather the generation.

2. WP Social Login
How is this check performed? What is verified? The problem is not qTranslate directly but the context in which it is used. I have many plugins using `plugins_url` together with qTranslate-XT active and it works without problem. So it's another very specific case that require further analysis.

**Comment by sviluppomania** [comment] 2019-06-12 10:29
QTranslate xt generates redirects backend / frontend, I explained all the technical problems.  The problem is qtranslate ... If you have solutions otherwise I recommend finding other language plugins.

**Comment by herrvigg** [comment] 2019-06-12 10:42
About the redirects i have asked you several times questions you still have not answered! As i already told you, some redirects are normal, and saying "the problem is qTranslate" is really of no help. I spent already some time helping you and giving you many directions for the investigation. This is a free community-driven plugin so it requires more effort from the users for the fixes, especially in such a complex integration environment like WP. You are part of the community and as a developer you are able to do much more, at least if you want your specific issues to be fixed. Feel free to try other plugins, maybe others are more suited for your usage.

I close this for now, you can re-open it if you provide more info but it requires you to do more investigation.

**Closed by herrvigg** 2019-06-12 10:42 UTC
Labels: integration
