### ISSUE TITLE
Causing Infinite Looping On Post Type

### ISSUE THREAD

**Issue by agitnaeta** [qtranslate/qtranslate-xt#791] opened 2020-02-28 09:25 UTC
Hello i try using this plugin :

when i try to `Trash` the post (the default one)
the url redirecting infinite to `url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en`

i already try this case but look like not working 
https://github.com/qtranslate/qtranslate-xt/wiki/FAQ#browser-redirections

**Comment by herrvigg** [comment] 2020-02-29 13:00
hello,
the trash function works normally for me. There's no chance i can fix this issue if i can't reproduce it or understand the context when it happens. Please try to describe the problem better and take a look at [Troubleshooting](
https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting) section that may give some tips.

- from where are you sending the post to trash?
- which plugin and versions are you using?
- which URL mode in qTranslate-XT?
- what is the `url` query string? This is not standard qTranslate

**Comment by agitnaeta** [comment] 2020-03-02 02:22
**1. i sending post to `Trash` from the admin side** 
 after i do trace this coming from -> https://github.com/qtranslate/qtranslate-xt/blob/master/qtranslate_core.php#L93

**2. Version that i create** 
Requires at least: 3.9
Tested up to: 4.5
Stable tag: 3.4.6.8
License: GPLv3 or later

3. im using permalink type `Day and Name`

**4. This the recursive part when i try to hit** 
`wp-admin/post.php?post=1452&action=trash&_wpnonce=22b43a7d40`
its becoming 
`/en/?url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&url=en/&trashed=1&ids=1456`

**Comment by herrvigg** [comment] 2020-03-02 19:44
> 2. Version that i create
> Requires at least: 3.9
> Tested up to: 4.5
> Stable tag: **3.4.6.8**
> License: GPLv3 or later

What do you mean with "version you create"? This looks very wrong. Are you sure you are using qTranslate-**XT**? It should be version **3.7.2** now. Many redirection issues have been fixed in -XT compared to -X (which is abandonned). Be sure to read properly the README.

**Closed** 2020-03-10 19:58 UTC
Labels: core, invalid
