### ISSUE TITLE
Test results: two errors remaining if I disable Woocommerce support plugin

### ISSUE THREAD

**Issue by The3IC** [qtranslate/qtranslate-xt#670] opened 2019-04-16 18:46 UTC
Have been now testin -XT 3.5.5 with latest 3.6-rc2. Everything seems good if I use -XT + old support plugin. Only 2 annoyances appear if I disable the WC support plugin (legacy):

- if I have added translated text on the WC shop page, then the text is not translated but the [..] [..] [:] format is visible

- the product name on the checkout page is overwritten with a non-translated string

It would be great if these 2 could be rolled into -XT, then I could get rid of one more plugin.

**Comment by herrvigg** [comment] 2019-04-16 20:35
Thanks for testing!

> Have been now testin -XT 3.5.5 with latest 3.6-rc2. 

What is that 3.6-rc2 corresponding to? If you mean you are using 3.6.0.dev then it's not 3.5.5 anymore.

> Everything seems good if I use -XT + old support plugin. 

Which version for the old support plugin (there are 2 different sources 1.3 or 1.4)?

> Only 2 annoyances appear if I disable the WC support plugin 

If you are using -XT 3.5.5 you don't have the modules so i suppose you are using the master branch (3.6.0.dev). But i need to understand very precisely which versions you were/are using.

**Comment by The3IC** [comment] 2019-04-16 20:52
3.6-rc2 is Woocommerce 3.6 "almost done" version so not the -XT version which is 3.5.5. (did not know you planned a 3.6 for -XT, cool :-) )
The old support plugin in 1.3

So, to be clear: 
qT-XT 3.5.5 alone -> 2 problems (shop page and checkout product name not translated)
qT-XT 3.5.5 + old 1.3 -> no problems (on my setup)

All test done on Woocommerce 3.6-rc2

**Comment by herrvigg** [comment] 2019-04-16 20:57
Thanks! But if you have 3.5.5 alone what do you expect from qTranslate-XT? It won't do anything specific for WC. You should try either:
- 3.6.0.dev: from master, or you can just download the master branch as an archive. This is the most interesting for me since i'm finalizing it. The module for WC corresponds to the old plugin WC+qTranslate 1.4.
- 3.5.5 + old plugin 1.4 (the one that i converted to module). But i would prefer the first option for better checks.

**Comment by herrvigg** [comment] 2019-04-17 14:42
Could you retry with the current version from master? You can download the archive from the clone button. Just think to deactivate/reactivate qTranslate-XT. Note the version in the readme is still 3.5.5 (to not trigger github updates) but the internal version is 3.6.0.dev. This makes the support plugins unnecessary, you will get notices anyway if you try to use the legacy stuff at the same time.

**Comment by The3IC** [comment] 2019-04-17 17:08
OK, I'll give it a shot over the holidays!

**Comment by herrvigg** [comment] 2019-04-17 23:01
The main part is ready now. Mostly doing cleanup and refactoring but i expect to release this soon so yes it would be good if people can take a look at it before.

Don't expect any big fix in WooCommerce but at least there should not be regressions. Also, i want people to use the new modules so we can finally drop these old plugins that are so annoying, especially for WooCommerce (there is still this big confusion between releases 1.3 and 1.4). From that point it should be much easier to handle the fixes with a single repo! But for these specific parts i mostly count on you guys - you are the real users ;)

**Comment by herrvigg** [comment] 2019-04-17 23:16
For more info about the changes concerning the modules check also https://github.com/qtranslate/qtranslate-xt/issues/661. Actually it's easier if we keep only that ticket so i close this one here. We should really try to focus on the new modules from now, for WooCommerce it is equivalent to plugin 1.4. You are much welcome to report your tests with the modules there :)

But if you run preliminary tests without the modules on 3.5.5 + support plugin 1.4 you can still report them here if you want. No need to re-open the ticket, i will get the notifications anyway.

**Closed by herrvigg** 2019-04-17 23:16 UTC
Labels: help wanted, integration
