### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by alaghi000** [qtranslate/qtranslate-xt#1127] opened 2022-03-20 21:38 UTC
I am getting error 404 when changing languages. If I refresh the website after a while (on the 404 error page), the right page loads correctly.
domain quintaessentia.com.br
Turning on debug mode, I see no related error in the log files.

**Comment by alaghi000** [comment] 2022-03-20 22:04
Looks like the problem can be solved changing the URL options on the plugin settings.
When using a different domain for each language, I had no more 404 errors.
<img width="1250" alt="Captura de Tela 2022-03-20 às 19 03 18" src="https://user-images.githubusercontent.com/65984664/159187904-d1391d5e-5068-4d08-8ca4-e616e303acc6.png">

**Comment by herrvigg** [comment] 2022-03-25 22:35
To understand well, you were using another URL mode giving you 404 errors, before switching to the domain mode? Which URL mode was it?
If it behaves differently after some refresh this doesn't feel like a problem in QTX but rather something with the web server or more specifically a cache server.

**Comment by alaghi000** [comment] 2022-03-26 12:08
I were using the pre-path mode, that results in intermittent 404 errors. I couldn't find what causes the problem. No log points it out.
I've found other people having the same issue in forums, but no solution for the problem. Some migrated to other translation plugins, but I don't wish to migrate.
It was solved using different domains for each language. It just worked out.

**Comment by alaghi000** [comment] 2022-03-28 13:56
I don't have the qtranslate-slugs plugin. Shall I install it?
when qtranslate is active everything gives 404 intermittently, except the administration page.
When I deactivate qtranslate, it stops giving 404, but my page does not work because of the theme used.

**Comment by spleen1981** [comment] 2022-03-28 14:40
> I don't have the qtranslate-slugs plugin. Shall I install it? 

No if you don't need it

>> After changing the url modification mode, try to go to permalink settings page and click on "Save Changes" button, that should trigger flush_rewrite_rules().

Did you try this?

> When I deactivate qtranslate, it stops giving 404, but my page does not work because of the theme used.

Not very clear, but you may try with a WP standard theme and qtranslate activated, just to make sure the issue is not related to your theme.

>> Which kind of content gives 404? post, homepage, custom post type?

?

**Comment by herrvigg** [comment] 2023-04-13 07:26
No update so I close this ticket. Re-open if you can provide more relevant data and how to reproduce it.

**Closed by herrvigg** 2023-04-13 07:26 UTC
Labels: need info, core
