### ISSUE TITLE
Language not working in widgets

### ISSUE THREAD

**Issue by hubosh** [qtranslate/qtranslate-xt#616] opened 2018-11-20 10:40 UTC
I just started using qTranslate XT and I was hoping for a fix to this problem.
When using text in a widget I can't change the languages, it just copies the last data I entered and stores it in all language tabs.

**Comment by herrvigg** [comment] 2018-11-20 11:33
Can you give more details about this problem? I guess you are referring to switching tabs but i can't see in which context. The widgets in the sense "qtranslate Widget" are meant to change language on the front-end so there's no data to enter there. So i suppose it's an admin page but which one? A screenshot could also help.

**Comment by herrvigg** [comment] 2018-11-20 11:40
About the widget admin menu, the only translatable field is the title and this works fine for me.

![image](https://user-images.githubusercontent.com/19155375/48771333-6e68b800-ecc1-11e8-8017-386b3c241f73.png)

**Comment by hubosh** [comment] 2018-11-20 13:12
> Can you give more details about this problem? I guess you are referring to switching tabs but i can't see in which context. The widgets in the sense "qtranslate Widget" are meant to change language on the front-end so there's no data to enter there. So i suppose it's an admin page but which one? A screenshot could also help.

What I meant is when I use text in a widget, I can't translate it, not even the title.
Here's a screenshot
![screenshot 2](https://user-images.githubusercontent.com/24465260/48775789-2193da00-ecdf-11e8-8a0e-71005909ea60.png)

**Comment by forexmd** [comment] 2018-11-20 16:10
I also have problem with translating widgets, on old qtranslate-x and the same on qtranslate-xt , which i just installed. When i save some text on one language immediately appears the same text for the second language. Do you have any idea how to make it work normal. Website forex.md . Thanks

**Comment by herrvigg** [comment] 2018-11-20 20:30
OK now i see, i can reproduce the problem. The input and textarea fields don't have the blue marker, which means they are not considered as translatable but i guess they are supposed to be part of those. I tried quickly to update the json config but it didn't work. I'll see if i manage to fix it.

**Comment by forexmd** [comment] 2018-11-20 21:04
whatever it is worth, the problem is only on the latest version of WP. With previous version of WP, was no problem, i have always made changes in footer/widgets before and had no problems with that.

**Comment by herrvigg** [comment] 2018-11-20 21:17
Oh i thought it was a much older problem.
If you look into i18n-config.json the selectors are `input[id^='widget-'][id$='-title']` and `textarea[id^='widget-text-'][id$='-text']` but this does not hold anymore. I tried other selectors simply with `input.title` and `textarea.text` but it doesn't work. At least we know the `widget-right` selector works as the switching tabs are shown.
Also i'm not sure why there are some similar selectors in `widgets-exec.js`, i thought this was supposed to be done with the json file only. If someone finds a solution let me know.

**Comment by herrvigg** [comment] 2018-11-20 23:41
Mmmm this looks more problematic than it first appeared. All these elements are created dynamically under `div.text-widget-fields` which does not exist when the page is loaded... but only when the drop down button is clicked.

I don't think such behavior exists in any other UI element. Technically it should still be possible but it becomes more complex and i'm not sure what is the best solution. Any suggestion welcome.

**Comment by herrvigg** [comment] 2018-11-28 12:38
I found more info about the underlying changes. It came with WP 4.8 (May 2017!) so that's not really new but no qTranslate handles this yet. 

https://make.wordpress.org/core/2017/05/23/addition-of-tinymce-to-the-text-widget/

Since the new Widget is using TinyMCE it should be possible to make it work as for the Classic Editor. But i don't know yet how to do so properly.

**Comment by forexmd** [comment] 2018-11-29 15:33
@herrvigg  thanks for help. It took me a lot of time to realize that the problem was in my .htaccess file, there has been added a command .
 <IfModule mod_headers.c>
Header set Referrer-Policy "origin"
</IfModule>
and for some reason this command brought up the issue. I removed it and work like a charm. Thanks again

**Comment by herrvigg** [comment] 2018-11-30 13:02
Mmm now i'm quite confused. Good if this solved something but i'm not sure we talk about the same things. Imo there is still a problem. How can the new text widget work? How is the translation managed in the edit boxes? Do you have the blue line on the left side of the title and the content?

**Comment by hubosh** [comment] 2018-12-09 07:12
> I found more info about the underlying changes. It came with WP 4.8 (May 2017!) so that's not really new but no qTranslate handles this yet.
> 
> https://make.wordpress.org/core/2017/05/23/addition-of-tinymce-to-the-text-widget/
> 
> Since the new Widget is using TinyMCE it should be possible to make it work as for the Classic Editor. But i don't know yet how to do so properly.

Yeah it's an old issue with qTranslate X, I once found a solution that includes downloading a plugin called Classic Text Widget. hope that can help.
Thanks for your amazing effort.

**Comment by dreamliner789** [comment] 2020-02-23 12:32
I installed today the new translate-xt. 
It seems to work wonderful and fine. Thanks to all who work on that helpful plugin. 

But the bug with the widget translation is not solved in my case. 
I tried to handle it with the recommended "Classic Text Widget" but that doesn't show me the true text in backend and doesn't works with html code. 
The lines with header and policy is not written in my htaccess. 

Did someone made the same experience and could solve this issue? 
Thanks for any help and recommedations.

**Comment by herrvigg** [comment] 2020-05-03 20:56
Here also i'm a bit lost with all the different widgets and screens. What is this issue exactly about?
- It seems the widget works when used from /wp-admin/widgets.php
- but not from /wp-admin/customize.php

Is that the problem raised here? Is it for any widget or for a specific plugin?

**Comment by Hr0bar** [comment] 2020-11-02 22:30
No, the opposite is true, it doesnt work at:
/wp-admin/widgets.php
it works at:
/wp-admin/customize.php

Here you can see a video of the latest XT, all kinds of bugs happen, not all were captured in the video...

https://www.youtube.com/watch?v=dA03SXlyhLg&feature=youtu.be

https://www.youtube.com/watch?v=FyChSDyRiXA&feature=youtu.be

**Comment by forexmd** [comment] 2020-11-20 19:28
hI, I am having troubles with QTranslateSlug. The field that we add the
translation disappeared from the page editor. Any Idea how to fix it?
Thanks

**Comment by herrvigg** [comment] 2021-06-26 14:05
Finally, a new solution to fix the text widget is now made available by #1042.

**Comment by Hr0bar** [comment] 2021-06-26 14:31
Awesome !! Thank you a lot for this.

**Comment by herrvigg** [comment] 2021-08-04 21:38
Merged in master for testing.

**Comment by herrvigg** [comment] 2021-08-28 21:49
Released in 3.11.0.

**Closed** 2021-08-29 08:55 UTC
Labels: bug, help wanted, severity: major
