### ISSUE TITLE
Include qtranslate slug into -XT

### ISSUE THREAD

**Issue by The3IC** [qtranslate/qtranslate-xt#671] opened 2019-04-22 11:40 UTC
Now that the -XT work is progressing so well, I would like to request that the old qTranslate slug be integrated. At this time it works still well with -XT but to make sure that this very valuable functionality is maintained with -XT, it would be great if it was made part of -XT.

https://github.com/not-only-code/qtranslate-slug

**Comment by herrvigg** [comment] 2019-04-22 20:51
Sure it would be good to have, but it's not my priority for now.

As i mentioned in https://github.com/qtranslate/qtranslate-xt/issues/660, the problem is qTranslate slugs has not been updated for 3 years and it has a lot of open issues:
https://wordpress.org/support/plugin/qtranslate-slug/

The git repo is not fresh either and there are also many open issues without answer:
https://github.com/not-only-code/qtranslate-slug/issues

Even if it looks okay for some people, I will definitely not merge a plugin in that state. better to keep it separated at this point. It would be good to have the authors involved, but the first step would be to refresh the plugin even before talking about merging it here. What you (or anyone else interested in this) can do is start to contact them on their repos and tell we are reviving qTranslate(-X/XT) so they can also start to revive their stuff ;)

The other option is to have new persons dedicating their time on that. A lot of testing would be required and then it can goes in with a PR but i am quite reluctant to merge something risky without the full knowledge the original authors had so i would definitely prefer the first option.

**Comment by gm-style** [comment] 2019-04-28 08:06
Hi there, I'm actively testing your new qT-XT with some popular plugins (woocommerce, ACF and Yoast) and latest WP versions. Actually I installed the "old" qT Slug plugin and it seems working like a charm, even with WC categories. I didn't find any issues atm but I'll keep testing.

**Comment by The3IC** [comment] 2019-04-28 18:38
> Actually I installed the "old" qT Slug plugin and it seems working like a charm, even with WC categories. I didn't find any issues atm but I'll keep testing.

qT Slug (as qT itself) work amazingly well considering they have gone a couple of years without maintenance. This just speaks a lot about the good initial architecture (compare to the constant flow of WPML problems). However, there are a number of quite important error reported over in the qT Slug repo, that would deserve getting fixed. In my view the worst problem is that the Slug breaks subpages. There are also problems with taxonomies (mainly "follow-on problems such as problems with SEO etc) and personally I'm sorely missing the capability to add language specific URLs in the Menus.

In general all (reasonably) successful language extensions do support slug translation so therefore I think is quite important for XT to have that functionality to get seriously back in the game!

(The fundamental problem is ofcourse the lack of a "native" multilingual support which is a glaring weakness of the whole wordpress platform. Pray that WPML is not rolled into wp core. Ugh.)

**Comment by The3IC** [comment] 2019-04-28 18:40
psm @herrvigg , I exchanged a couple of messages with author (not-only-code) and apprantly he has no intention of getting back to qT slug and is quite happy to have some fork it.

**Comment by bagaweb** [comment] 2019-04-30 07:23
> In my view the worst problem is that the Slug breaks subpages.

I didn't encounter this problem. Not even on sub custom post types.

**Comment by herrvigg** [comment] 2019-04-30 11:23
Good that qT-slug works reasonably well although it didn't get any update over these years. But it feels a bit premature to merge it completely given the current state of both plugins and the transformations happening in qT-XT.  Unlike the modules that were only for integration purpose, qT-slug is a whole new functionality. Merging it will generate extra work, with new issues and more code to maintain so it will rather slow down qT-XT. Therefore at the moment i'm more reluctant to add this, but i'm quite confident it will happen at some point.

It's sad that the author (not-only-code) doesn't want to update his plugin. But seen that his repo is the reference, wouldn't the best solution for now to ask him to give permissions to more people to act on his repo directly? Forks add more complexity and the information gets diluted. His repo has the main commit history and the most significant issues so it's always better to act on a single repo as much as possible. My point of view is that the preliminary work should be done there also to give some time for qT-XT to undergo its transformations independently.

**Comment by sailinf** [comment] 2019-10-11 16:53
While 3.7.0 did removed the big problem with possible data loss, it seems that there was some negative impact on interaction with qt Slug. Haven't done a very exhaustive test but seems that menu items now work less well and items end up being posted with "mixed" urls. After language switching back and forth, it does get it right.

So dispite the wontfix, still a small reminder that the language-based URLs would be very valuable for qTranslate-XT.

**Comment by herrvigg** [comment] 2019-10-13 13:22
To the slug users: this plugin is lying too much behind for an easy fusion in qT-XT, it's been more than 3 years it has not received any update. On my side, it would take me too much time and effort to get it up to a decent level and this would create me too much extra work. I am currently working on Gutenberg, critical bug fixes and all kind of refactoring so i can't deal with that now. It's already quite a pain trying to maintain the legacy compatibility just for slug... Meanwhile, i strongly recommend someone clone this plugin and fix the pressing issues separately. This would also allow for the next evolutions to come. This clone could be part of the current qtranslate group for better visibility, but i will not be involved with it.

**Comment by herrvigg** [comment] 2019-10-13 13:31
Also, once qT-XT moves to a new repo, there will be many, many breaking changes in core, the API and all the integration framework. So someone will **have** to make it live with the next evolutions or this will become hardly unusable, at least for some time.

**Comment by bagaweb** [comment] 2019-10-15 16:42
As said in #743 haven't found any issues with qT-XT 3.7.0 and qT-slug. I'd love to help with the slug plugin but my coding skills are not enough.

@herrvigg what do you mean with:

> This clone could be part of the current qtranslate group for better visibility

**Comment by herrvigg** [comment] 2019-10-15 21:17
At some point it -slug will certainly be merged in the the main plugin but for now i prefer to avoid it because i have to focus on the rest and this would slow me down. I don't think there is so much work but at least if someone can start with it that would be time saved for later, because the changes are going to be inevitable.

What i meant for the visibility was just this group on github: https://github.com/qtranslate.

The plugin on WordPress is getting very old now... better having something only available on github than a very obsolete plugin.

Btw WordPress has still a big problem to solve with the fact they don't properly support Composer. Though we don't really need it with qTranslate because we have zero dependency, there is still the question related to the autoloaders. In general it's becoming more and more a problem for the developers that the deployment with WP is still so archaic with the plugin interface.

**Comment by herrvigg** [comment] 2019-10-20 21:31
Someone pushed an obsolete version to https://github.com/qtranslate/qtranslate-slug. This looks like the initial version from 2012, but the last commit is 2016 in the original repo https://github.com/not-only-code/qtranslate-slug.

I know that repeating the change described in #743 at every qTranslate-XT update is a bit annoying. We should at least find a fix for that.

On my side, -slug is quite annoying to maintain but i'm now wondering if maybe the best would be to merge it anway in -XT as it is. I would not work on it, because i would not even have the way to test it, but this may allow to change the API and some hooks more easily.

The idea, if i merge it, would not be a bit similar to a module, but slightly different. Rather a beta-feature that would be turned off by default and it would be up to you to validate if after each release (hopefully things should not break).

It's still not clear to me if the slug in development coming from -X is worth keeping or if we should throw this away. If -slug does the job we should rather keep this one.

**Comment by herrvigg** [comment] 2019-10-20 21:37
Overall, the -XT transition would allow to gather all the most important plugins in a single repo. This was my main idea since the beginning, so that it finally enables the VERY-MUCH-needed refactoring in qTranslate core. The main framework for PHP and JS are completely out of fashion and it becomes an absolute nightmare to maintain, despite some preliminary refactoring. But now i'm really stuck by the API, i have already in mind a huge number of changes that are going to be breaking (from an API perspective).

**Comment by bagaweb** [comment] 2019-10-22 08:55
It was probably my fault, I'm not very familiar with GitHub, how can I fix this mistake?

**Comment by herrvigg** [comment] 2019-10-23 09:12
No worry, i removed it for now. I think it's better if i merge it, but i don't when i will do it.

**Comment by bagaweb** [comment] 2019-10-23 09:49
Ok thanks.

**Comment by benjibee** [comment] 2020-04-28 16:56
I'd love to see this merged as an option to turn on / off with a little warning for those of us who are willing to take that risk. Once I have a bit more time I'd be happy to look into some small PRs to work it towards something more modern.

 I know you (@herrvigg) don't have a personal use for it but image having a page titled _All About Cats and Dogs_ in English, and _Alles Über Katzen und Hunde_ in German, it's very odd indeed to have a slug _all-about-cats-and-dogs_ showing and being shared amongst German visitors.

There really is no good alternative to qTranslate out there!

**Comment by herrvigg** [comment] 2020-05-01 11:24
@benjibee now that we have at least a baseline for Gutenberg the next big step is preparing the migration to the new repo and official plugin which is the big milestone hopefully soon.

I'm not entirely against integrating slug but it is very, very complex to test with a billion problems of integration and the current state of qTranslate is still quite a mess so i can't really ensure it will work. 

But if we consider it as a kind of experimental feature it might still be possible to do something. The main reason would be to simplify the interface. We may give a try on a separate branch first.

The first question would then be which plugin to start from. I've read recently from @spleen1981 that `qtranslate-slug` has also been forked in `130-unique-slug` (https://github.com/qtranslate/qtranslate-xt/issues/805). So it would be good if all the qtranslate-slug users here discuss about this and agree what could be the base version to start from.

**Comment by herrvigg** [comment] 2020-05-01 11:28
Correction, it's not a fork but a branch in qtranslate-slug itself: https://github.com/not-only-code/qtranslate-slug/tree/pcarvalho/fix/130-unique-slug

**Comment by bagaweb** [comment] 2020-05-01 13:15
Thanks for the link @herrvigg, I didn't know about this fork, will try to test it right now.

**Comment by benjibee** [comment] 2020-05-01 15:42
@herrvigg thanks for this, I know there's a lot in transition right now. I just ran into a situation where the client really insisted on translated slugs and I dreaded the thought of having to implement and maintain WPML.

If I weren't already overworked I'd dig around in the plugin and offer a PR myself!

**Comment by bagaweb** [comment] 2020-05-01 17:20
This 130-unique-slug fix doesn't work for me, it gives 404 on home page.

**Comment by spleen1981** [comment] 2020-05-01 21:36
> @benjibee now that we have at least a baseline for Gutenberg the next big step is preparing the migration to the new repo and official plugin which is the big milestone hopefully soon.
> 
> I'm not entirely against integrating slug but it is very, very complex to test with a billion problems of integration and the current state of qTranslate is still quite a mess so i can't really ensure it will work.
> 
> But if we consider it as a kind of experimental feature it might still be possible to do something. The main reason would be to simplify the interface. We may give a try on a separate branch first.
> 
> The first question would then be which plugin to start from. I've read recently from @spleen1981 that `qtranslate-slug` has also been forked in `130-unique-slug` (#805). So it would be good if all the qtranslate-slug users here discuss about this and agree what could be the base version to start from.

@herrvigg, my feedback for '130-unique-slug' was given since it was specifically requested [here](https://github.com/qtranslate/qtranslate-xt/issues/608#issuecomment-420823032); as per that feedback, it seems that this branch is not usable currently.
On the other hand, 'qtranslate-slug' is working reasonably good even with latest qtranslate-XT, that is why I would suggest to use it as starting point for future inclusion in '-XT'.

**Comment by herrvigg** [comment] 2020-09-27 10:58
For evolutions of the API i'm just identifying the functions used by qtranslate-slug:
```
qtranxf_convertURL
qtranxf_getLanguage
qtranxf_getSortedLanguages
qtranxf_split
qtranxf_use
qtranxf_useTermLib
qtranxf_wp_head
```

**Comment by herrvigg** [comment] 2021-08-29 08:46
For the qtranslate-slug users:

As said, we may integrate qtranslate-slug as an **experimental feature** in qTranslate-XT. That means to **maintain** the code from a low level point of view, ensure the API calls are correct and make it consistent with the rest.

However I would not be able to **test** this properly since this requires specific setup and time to do so. So this is rather up to the users/developers - you! You should be many enough to do so. Any help with the code is also welcome.

You should first agree on which code to merge and send a pull request.

**Comment by spleen1981** [comment] 2021-08-31 18:11
hi @herrvigg I've been using qtranslate-slug plugin v1.1.8 (latest stable release), without particular problems for years now. That version is what I would include in the main plugin.
Tried to contribute with PR #1060.
From a quick check for my use case (including woocommerce) it seems to work more or less as previously (just disabled qtranslate slug and patched qtranslate-xt) with a couple of warnings to be fixed.
I guess first step should be to confirm that merge was not too "raw", more checks on my side will follow.

Lot of work yet to be done, but still it's a first step.

**Comment by herrvigg** [comment] 2021-08-31 22:30
Awesome! Looks great! I will look at it in the next days.

**Comment by bagaweb** [comment] 2021-09-01 10:03
> 
> 
> hi @herrvigg I've been using qtranslate-slug plugin v1.1.8 (latest stable release), without particular problems for years now. That version is what I would include in the main plugin.
>
I confirm version 1.1.18 is still working, I've been using it in about 70 projects.

**Comment by benjibee** [comment] 2021-09-02 14:36
While I haven't used it in 70 projects (🤯) I can say from my end this looks to be a stable and reliable solution to the problem. I'd be happy to test any potential PRs, etc.

**Comment by herrvigg** [comment] 2022-02-13 23:20
The PR #1060 is now merged in master!
There's still a lot of refactoring to do but now the functionality should be there and it should be easier to rework this part.
Main things to do:
- remove the legacy code related to the plugin, refactor activation/deactivation
- integrate the QTS settings in the QTX panel directly 
- code cleanup, harmonize code, variables, style, ...
- I haven't tested the JS part at all (I trust you for the current state) but there is surely quite some rework there as well.

Now it's up to the users to spot the bugs. Better with new tickets if it's about new topics.
I'll leave this topic open for a short time for visibility and conclude but I will close this ticket soon.

**Comment by herrvigg** [comment] 2022-02-13 23:26
There's a minor bug when enabling the slugs module, it appears still disabled the first time but if you refresh the page it will appear enabled. To be fixed.

**Comment by The3IC** [comment] 2022-02-14 07:19
Great news!

**Comment by bagaweb** [comment] 2022-02-15 11:03
Excellent news!

**Comment by herrvigg** [comment] 2022-02-17 22:31
That plugin is so old it created the table `wp_termmeta` on its own (!)... it was before WP 4.4. I'm removing a lot of obsolete stuff, I hope I won't break anything so please test regularly from `master`.

**Comment by bagaweb** [comment] 2022-02-18 13:37
I will test it, thanks @herrvigg :)

**Comment by herrvigg** [comment] 2022-02-19 11:38
Also, a big shoutout to @not-only-code @LC43 @pedro-mendonca who are the main contributors of the original [qtranslate-slug plugin](https://github.com/not-only-code/qtranslate-slug)! 👏💯  
As you may know, qTranslate-XT is the evolution of qTranslate-X, abandoned since 2016 and QTS stopped evolving from that date. We have now merged QTS into QT-XT so the slug functionality can continue to live and evolve! The contributors of the original plugin are credited. We'd also be much happy if you could contribute here. Your knowledge would be much appreciated.

**Comment by spleen1981** [comment] 2022-02-19 16:07
> There's a minor bug when enabling the slugs module, it appears still disabled the first time but if you refresh the page it will appear enabled. To be fixed.

fixed by #1107

**Comment by herrvigg** [comment] 2022-02-19 18:10
Merged #1107, nice!

**Comment by sviluppomania** [comment] 2022-02-21 20:58
https://github.com/qtranslate/qtranslate-xt/issues/1108
Who knows the Plugin to also integrate? :-)

**Comment by herrvigg** [comment] 2022-05-09 21:34
Merged in master, finalizing last changes before release.

**Closed by herrvigg** 2022-05-09 21:34 UTC
Labels: enhancement, help wanted, module: slugs

**Comment by herrvigg** [comment] 2022-05-29 13:44
There's a new migration feature from QTS now merged in master. The release 3.12.0 is approaching. Please test this and let us know how it goes.

For follow-up and comments please write in this discussion: https://github.com/qtranslate/qtranslate-xt/discussions/1106#discussioncomment-2843673
