### ISSUE TITLE
Second language being overwritten by default language

### ISSUE THREAD

**Issue by sailinf** [qtranslate/qtranslate-xt#722] opened 2019-08-20 12:19 UTC
I've had an issue more or less for the whole time I've been using qTranslate-X and now the same issue is still with -XT.

The problem is that some times (and I don't really know exactly what triggers it), when I edit a page, the second language gets' overwritten by the default language. So for instance, the sites default language is fi with en being the other. Sometimes, the en "page" gets totally replaced by the fi text. This happens specifically (and only) for the fields being directly supported by qTranslate in the LSB mode. So for instance page content, SEO strings etc. 

Strings not directly supported (eg for which I edit in the :fi....:en format are not affected.

Has anyone else seen this problem? It's most annoying with Woocommerce products as there is no version saved, for pages it is still reasonably easy to recover.

This seems to be more likely if:
a) I have multiple windows open for editing
b) I only edit on language version (meaning I don't touch the LSB buttons).

Cache is disabled for admins so this is not a simple cache issue.

**Comment by janeschindler** [comment] 2019-08-20 12:25
Did you see #496 ?

**Comment by sailinf** [comment] 2019-08-20 12:38
Ah, I tried search but clearly did not find the right words. Yes, my issues seems to be the same. If this was fixable, it would be great, it is super annoying when it happens on products :-(

**Comment by herrvigg** [comment] 2019-09-22 09:28
To clean the backlog i will close this one as it is a duplicate of https://github.com/qtranslate/qtranslate-xt/issues/496. This case is about the multiple tab.

The other issue about overwriting from single tab is different. In that case, refer to this one: https://github.com/qtranslate/qtranslate-xt/issues/724.

**Closed by herrvigg** 2019-09-22 09:28 UTC
