### ISSUE TITLE
ACF PRO 6.0.7 - cannot see option to create qTranslate fields

### ISSUE THREAD

**Issue by dragonwear** [qtranslate/qtranslate-xt#1291] opened 2023-03-13 17:47 UTC
Hello,

with newest ACF PRO 6.0.7 i cannot see option to create qTranslate fields.
When creating custom field, qtranslate fields are not seen there,
thus unable to create one.

It works on site with ACF PRO 6.0.5 and latest qtranslate-xt

Using the latest version of qtranslate-xt.

This problem was here before, so I am curious if someone has the same problem or can give me some
guidance how to fix it.

Kind regards,  me

**Comment by herrvigg** [comment] 2023-03-13 20:52
I tried with ACF Free 6.0.7 and I can't reproduce the problem.
I can see all the "qTranslate-XT extended fields" when I edit a group field, if this is what you mean by "creating a custom field".
Are you using the latest version on github (`master` branch) or the last release 3.13.0?

I'd like to deprecate the "qTranslate-XT extended fields". Consider switching to **standard ACF fields** like text, textarea and wysiwyg. These are the ones we should keep.

**Comment by MKRD-SUPPORT** [comment] 2023-03-14 18:44
In my quick check with PHP 8.x and QTX 3.13, I was not able to reproduce the behavior described (group & QTX fields).

**Comment by herrvigg** [comment] 2023-03-14 23:35
No problem with PHP 8.2.0. It's something else, maybe another plugin creating troubles. What do you have? Try disabling all except QTX + ACF. Obviously, check that the ACF module is active and if translation of standard fields is working, there were many fixes with 3.13.0 including the initialization sequence.

**Comment by herrvigg** [comment] 2023-04-02 09:46
@dragonwear please retry with last release 3.14.0 and see the new settings. The redundant qTranslate fields are now deprecated, try using the standard ones. If you still see some problems give more information, I will close this ticket if there's no activity.

**Comment by herrvigg** [comment] 2023-04-13 07:22
No update so I close this ticket. Re-open if you can provide more relevant data and how to reproduce it.

**Closed by herrvigg** 2023-04-13 07:22 UTC
Labels: need info, module: ACF
