### ISSUE TITLE
Warning: assert(): language needs to be shown in url - cancelled by can_redirect failed in

### ISSUE THREAD

**Issue by LaMpiR** [qtranslate/qtranslate-xt#757] opened 2019-11-13 07:27 UTC
Hi.

So, got a notification that a new Wordpress version is out, wanted to do it from my phone with Chrome and this is the error I keep getting. I cannot login from my phone.

PHP | v7.2.24

> Warning: assert(): language needs to be shown in url - cancelled by can_redirect failed in /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php on line 109
> 
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/13/website/htdocs/website/wp-login.php on line 496
> 
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/13/website/htdocs/website/wp-login.php on line 512
> 
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/13/website/htdocs/website/wp-includes/functions.php on line 5946
> 
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/13/website/htdocs/website/wp-includes/pluggable.php on line 932
> 
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/13/website/htdocs/website/wp-includes/pluggable.php on line 933
> 
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/13/website/htdocs/website/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/13/website/htdocs/website/wp-includes/pluggable.php on line 934

**Comment by herrvigg** [comment] 2019-11-13 10:27
This looks like a duplicate of https://github.com/qtranslate/qtranslate-xt/issues/749. It's fixed in master but not released yet. 

So you can either use the current version from master or check your WP config for WP_DEBUG and disable it if you have it. A website in production should not use WP_DEBUG. If you don't have it there's something else in your PHP config triggering the asserts. This is only for development purpose.

**Comment by LaMpiR** [comment] 2019-11-13 10:33
Thank you for the quick reply. I am using the latest which is available through wordpress, should I upgrade from here?

WP_DEBUG is set to false, so it't shouldn't popup.

**Comment by herrvigg** [comment] 2019-11-13 10:38
WP_DEBUG is only a shortcut specific to WP but under the hood it enables some PHP error to pop up. So it's certainly some PHP configuration enabling the asserts. Normally those should remain quiet on a production setup, unlike the exceptions which are meant to trigger in any case.

You can try to download the current master branch directly. Compared to 3.7.1 there's only this patch so it's not "worth" doing a release only for this.

**Comment by herrvigg** [comment] 2019-11-13 10:40
You can find the link from the main page of this repo ("Clone or download"): https://github.com/qtranslate/qtranslate-xt/archive/master.zip

**Comment by herrvigg** [comment] 2019-11-23 15:20
@LaMpiR I think we can close this. If the fix works it will also come with the next release.

**Comment by LaMpiR** [comment] 2020-01-19 19:29
Hi. 

I still have the problem. It wasn't present until yesterday I think. I have the latest versions.

**Comment by alexisju** [comment] 2020-01-21 09:19
I also have this (very annoying) issue on website in production. I have to disable the plugin via SSH to be able to login...

**Comment by LaMpiR** [comment] 2020-01-24 13:04
Any news on the problem?

**Comment by alexisju** [comment] 2020-01-30 09:38
@herrvigg any suggestion? The tricks in the faq don't work. Cleaning cookies neither.. it is very painful as issue.

**Comment by herrvigg** [comment] 2020-02-19 21:49
@LaMpiR @alexisju are you using the last version on master?

**Comment by LaMpiR** [comment] 2020-02-19 22:08
> @LaMpiR @alexisju are you using the last version on master?

At the moment of writing once more, I have recheck the version and reuploaded the latest and still had the problem. I have managed to stay signed in and have not experienced the problem, since I didn't have any need to sign in once more.

**Comment by LaMpiR** [comment] 2020-02-19 22:27
I am using the version 3.7.1 with the latest wordpress and I have logged myself out, only to be greeted by this upon me trying to log back in.

> Warning: assert(): language needs to be shown in url - cancelled by can_redirect failed in /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php on line 109

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/1/htdocs/website.at/wp-login.php on line 496

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/1/htdocs/website.at/wp-login.php on line 512

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/1/htdocs/website.at/wp-includes/functions.php on line 6029

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/1/htdocs/website.at/wp-includes/pluggable.php on line 932

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/1/htdocs/website.at/wp-includes/pluggable.php on line 933

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/htdocs/website.at/wp-content/plugins/qtranslate-xt/qtranslate_core.php:109) in /homepages/1/htdocs/website.at/wp-includes/pluggable.php on line 934
Pokreće Vordpres

>

**Comment by herrvigg** [comment] 2020-02-19 22:52
As wrote earlier, the assert should not trigger any error on a website in production. This is only for debug purposes. So an easy way would be to disable the asserts (normally WP config, otherwise PHP settings). Another way would be to just comment the assert line 109 in qtranslate_core.php.

However the assert is also something i added recently to debug those crazy situations with the redirections. It shows there is something inconsistent in qTranslate state so this is something that would be really nice to understand and fix properly.

Here the case is `language needs to be shown in url` which is triggered line 453 in qtranslate_core.php so we can try to debug this. Can you send me first the version info in troubleshooting?

**Comment by herrvigg** [comment] 2020-02-20 00:07
What is your URL when you are trying to login? I don't really need the website but what follows. The default is `wp-login` but if you have something different this could explain the problem - maybe.

**Comment by alexisju** [comment] 2020-02-20 07:51
I'm trying to log in https://domain.com/wordpressfolder/wp-login.php

(Website accessible from https://domain.com/ but WP in installed in a subfolder configured to be not visible for visitors. ).

I use latest WP and qtranslate-xt installed from Github updater (currently 3.7.1 version).

my .htaccess:
```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /wordpressfolder/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpressfolder/index.php [L]
</IfModule>

# END WordPress

```

**Comment by LaMpiR** [comment] 2020-02-20 08:57
My login website is https://www.website.com/wp-login.php and my Wordpress is installed in root folder

PHP: 7.2.27
WP: 5.3.2
QTX: 3.7.1

My htaccess:

> # BEGIN WpFastestCache
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteCond %{HTTPS} =on
> RewriteCond %{HTTP_HOST} ^www.website.at
> # Start WPFC Exclude
> # End WPFC Exclude
> # Start_WPFC_Exclude_Admin_Cookie
> RewriteCond %{HTTP:Cookie} !wordpress_logged_in_[^\=]+\=itadmin
> # End_WPFC_Exclude_Admin_Cookie
> RewriteCond %{HTTP_HOST} ^www.website.at
> RewriteCond %{HTTP_USER_AGENT} !(facebookexternalhit|WhatsApp|Mediatoolkitbot)
> RewriteCond %{HTTP_USER_AGENT} !(WP\sFastest\sCache\sPreload(\siPhone\sMobile)?\s*Bot)
> RewriteCond %{REQUEST_METHOD} !POST
> RewriteCond %{REQUEST_URI} !(\/){2}$
> RewriteCond %{REQUEST_URI} \/$
> RewriteCond %{QUERY_STRING} !.+
> RewriteCond %{HTTP:Cookie} !comment_author_
> RewriteCond %{HTTP:Cookie} !wp_woocommerce_session
> RewriteCond %{HTTP:Cookie} !safirmobilswitcher=mobil
> RewriteCond %{HTTP:Profile} !^[a-z0-9\"]+ [NC]
> RewriteCond %{DOCUMENT_ROOT}/wp-content/cache/all/$1/index.html -f [or]
> RewriteCond /homepages//htdocs/website.at/wp-content/cache/all/$1/index.html -f
> RewriteRule ^(.*) "/wp-content/cache/all/$1/index.html" [L]
> </IfModule>
> <FilesMatch "index\.(html|htm)$">
> AddDefaultCharset UTF-8
> <ifModule mod_headers.c>
> FileETag None
> Header unset ETag
> Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
> Header set Pragma "no-cache"
> Header set Expires "Mon, 29 Oct 1923 20:30:00 GMT"
> </ifModule>
> </FilesMatch>
> # END WpFastestCache
> # BEGIN GzipWpFastestCache
> <IfModule mod_deflate.c>
> AddType x-font/woff .woff
> AddType x-font/ttf .ttf
> AddOutputFilterByType DEFLATE image/svg+xml
> AddOutputFilterByType DEFLATE text/plain
> AddOutputFilterByType DEFLATE text/html
> AddOutputFilterByType DEFLATE text/xml
> AddOutputFilterByType DEFLATE text/css
> AddOutputFilterByType DEFLATE text/javascript
> AddOutputFilterByType DEFLATE application/xml
> AddOutputFilterByType DEFLATE application/xhtml+xml
> AddOutputFilterByType DEFLATE application/rss+xml
> AddOutputFilterByType DEFLATE application/javascript
> AddOutputFilterByType DEFLATE application/x-javascript
> AddOutputFilterByType DEFLATE application/x-font-ttf
> AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
> AddOutputFilterByType DEFLATE font/opentype font/ttf font/eot font/otf
> </IfModule>
> # END GzipWpFastestCache
> # BEGIN LBCWpFastestCache
> <FilesMatch "\.(ico|pdf|flv|jpg|jpeg|png|gif|webp|js|css|swf|x-html|css|xml|js|woff|woff2|ttf|svg|eot)(\.gz)?$">
> <IfModule mod_expires.c>
> AddType application/font-woff2 .woff2
> ExpiresActive On
> ExpiresDefault A0
> ExpiresByType image/webp A2592000
> ExpiresByType image/gif A2592000
> ExpiresByType image/png A2592000
> ExpiresByType image/jpg A2592000
> ExpiresByType image/jpeg A2592000
> ExpiresByType image/ico A2592000
> ExpiresByType image/svg+xml A2592000
> ExpiresByType text/css A2592000
> ExpiresByType text/javascript A2592000
> ExpiresByType application/javascript A2592000
> ExpiresByType application/x-javascript A2592000
> ExpiresByType application/font-woff2 A2592000
> </IfModule>
> <IfModule mod_headers.c>
> Header set Expires "max-age=2592000, public"
> Header unset ETag
> Header set Connection keep-alive
> FileETag None
> </IfModule>
> </FilesMatch>
> # END LBCWpFastestCache
> # Wordfence WAF
> <Files ".user.ini">
> <IfModule mod_authz_core.c>
> 	Require all denied
> </IfModule>
> <IfModule !mod_authz_core.c>
> 	Order deny,allow
> 	Deny from all
> </IfModule>
> </Files>
> # END Wordfence WAF
> # BEGIN WPSuperCache
> # END WPSuperCache
> 
> # BEGIN rlrssslReallySimpleSSL rsssl_version[3.2.2]
> <IfModule mod_rewrite.c>
> RewriteEngine on
> RewriteCond %{HTTPS} !=on [NC]
> RewriteCond %{REQUEST_URI} !wp-content\/cache\/(all|wpfc-mobile-cache)
> RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
> </IfModule>
> # END rlrssslReallySimpleSSL
> # BEGIN WordPress
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteRule ^index\.php$ - [L]
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule . /index.php [L]
> </IfModule>
> # END WordPress

**Comment by herrvigg** [comment] 2020-02-20 10:14
@LaMpiR @alexisju Since your QTX_VERSION is showing 3.7.1 you were not using the very last version here on master, but i incremented it to 3.7.2.dev.1 after the first fix for #749 (which solved the problem) so let's clear it up.

Github updater can only detect new releases (on github), and the last fix i sent in #749 is not officially released yet. So you have to download manually. I takes a bit more effort but it's worth if it solves your issue and it really helps the community here. The QTX_VERSION is not necessarily updated after every commit in the master branch so it can create a bit of confusion. At any time, you can download the latest archive from https://github.com/qtranslate/qtranslate-xt/archive/master.zip. I will release this if you confirm it fixes your problem. 

Now i added even more relevant info for debugging in case the problem is still here, so we can understand better what's going on. I also incremented QTX_VERSION to 3.7.2.dev.2 to avoid confusions.

**Comment by herrvigg** [comment] 2020-02-20 10:23
In fact i could also update the version of the plugin differently and you could update with Github Updater: https://github.com/afragen/github-updater/wiki/Versions-and-Branches

Alternatively, we could create a specific branch for this problem and you could extract this with Github Updater that allows to select custom branches (in the options). I have to think about this and make it more convenient.

For now you can try to download the archive manually? Let me know how it goes.

**Comment by alexisju** [comment] 2020-02-20 10:28
Yes! It seems to works with the master. I just have installed it manually.
```
  "PHP_VERSION": "7.3.11",
  "WP_VERSION": "5.3.2",
  "QTX_VERSION": "3.7.2.dev.2",
```

**Comment by LaMpiR** [comment] 2020-02-20 10:35
@herrvigg thank you for the quick reply and your effort on this!

As @alexisju I have updated with the given link and this is the info. I have logged out and logged back in without any problems. I could not log in from my phone and it worked properly. Thank you once more. 

>  "PHP_VERSION": "7.2.27",
>   "WP_VERSION": "5.3.2",
>   "QTX_VERSION": "3.7.2.dev.2",
> 
>

**Comment by herrvigg** [comment] 2020-02-20 20:49
Great news! Nice to read :)

**Closed by herrvigg** 2020-02-20 20:49 UTC
Labels: bug, core

**Comment by herrvigg** [comment] 2020-02-21 12:43
@LaMpiR @alexisju To be complete about how the asserts are handled, first see: https://www.php.net/manual/en/function.assert.php. The main configuration is not about the WordPress configuration but from your PHP interpreter. There actually two levels:

Directive | Default value | Possible values
-- | -- | --
zend.assertions | 1 | <ul><li>1: generate and execute code (development mode)</li><li>0: generate code but jump around it at runtime</li><li>-1: do not generate code (production mode)</li></uk>
assert.exception | 0 | <ul><li>1: throw when the assertion fails, either by throwing the object provided as the exception or by throwing a new AssertionError object if exception wasn't provided</li><li>0: use or generate a Throwable as described above, but only generate a warning based on that object rather than throwing it (compatible with PHP 5 behaviour)</li></ul>

From this i deduce your config was:
```
zend.assertions = 1
assert.exceptions = 0
```
This means the asserts turn into a warning (E_WARNING). Now the fact that it is shown or not depends on your WP DEBUG configuration, more precisely the WP_DEBUG_DISPLAY. The PHP warnings are issued in any case (E_WARNING is reported even in WP_DEBUG mode), but here it's only a question of displaying the warning. From this i deduce your WP config is the following:
```
WP_DEBUG = true
WP_DEBUG_DISPLAY = true
```

This means you are in 100% dev mode. Normally in **production** you should have:
```
zend.assertions = -1 // skip for faster execution!
assert.exceptions = 0  // ... but we don't care because it's not executed
WP_DEBUG = false // also for faster for the WP/plugins code and no debug display
```
But... it's actually good you had all those things enabled... because it helps to understand the bugs in qTranslate! Seeing the asserts is very useful 😅 

I will add this to the wiki because the [WordPress doc about debugging](https://wordpress.org/support/article/debugging-in-wordpress/) is not mentioning the PHP part which is actually the most important.

**Comment by herrvigg** [comment] 2020-02-23 13:58
Updated Wiki [Troubbleshooting](https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting).
