### ISSUE TITLE
ACF and QTranslate XT image issue

### ISSUE THREAD

**Issue by gab1982** [qtranslate/qtranslate-xt#1241] opened 2022-10-28 10:16 UTC
Hi I have an ACF options Qtranslate XT image field however it isn't allowing me to set an image but if i change the field type to a normal image then I am able to set it but I would like to use the qtranslate xt image field as my site is multilingual, I am using Wordpress v6.0.3, ACF v6.0.3 and Qtranslate XT v3.12.1

**Comment by herrvigg** [comment] 2022-11-05 18:24
Can you explain/show what happens when you say "it isn't allowing me to set an image"?
I can't reproduce this, I tested for an image field displayed in a post and all works as expected.

**Comment by gab1982** [comment] 2022-11-05 18:27
Hi, thanks for your reply, I have attached a screenshot and on click nothing happens, i checked the console for errors but nothing shows.
<img width="345" alt="Screenshot 2022-11-05 at 19 26 06" src="https://user-images.githubusercontent.com/4854818/200135338-f8e4dcce-289b-4317-ab20-c5bf885a5d42.png">

**Comment by herrvigg** [comment] 2022-11-05 19:08
So that happens with a "image (qTranslate-XT)" field?
If you add a "Text (qTranslate-XT)" field does it work?

**Comment by gab1982** [comment] 2022-11-05 20:32
Yes seems to be ok with the text field, but when set to a Image (Qtranslate-XT) field i can't even delete or edit it unless i change it to a regular image field.

**Comment by herrvigg** [comment] 2022-11-05 20:47
That's really strange, because that "Add Image" button is not handled by QT-XT.
It's a good sign the text field works, which means most of the code is working.
Are you a PHP/JS developer?

**Comment by herrvigg** [comment] 2022-11-05 20:53
It could be due to some specific uploader. Are you able to compare the HTML code between the QTX-image field and the standard ACF-image field?

**Comment by herrvigg** [comment] 2022-11-05 20:57
I guess it worked with ACF5 and it's a recent regression with ACF?
I'd need to bisect the differences between ACF 5 and 6 but I suspect something about the type of uploader.

**Comment by gab1982** [comment] 2022-11-05 21:05
> That's really strange, because that "Add Image" button is not handled by QT-XT. It's a good sign the text field works, which means most of the code is working. Are you a PHP/JS developer?

sorry im not really a php/js developer, i know a bit but nothing too much

**Comment by gab1982** [comment] 2022-11-05 21:10
> It could be due to some specific uploader. Are you able to compare the HTML code between the QTX-image field and the standard ACF-image field?

here is the code:

default image field:

<div class="acf-field acf-field-image acf-field-612f30685384d" style="width: 20%; min-height: 237px;" data-name="popup_img" data-type="image" data-key="field_612f30685384d" data-width="20" data-conditions="[[{&quot;field&quot;:&quot;field_612ddaedec092&quot;,&quot;operator&quot;:&quot;==&quot;,&quot;value&quot;:&quot;1&quot;}]]">
<div class="acf-label">
<label for="acf-field_612f30685384d">Popup Img</label></div>
<div class="acf-input">
<div class="acf-image-uploader has-value" data-preview_size="medium" data-library="all" data-mime_types="" data-uploader="wp">
			<input type="hidden" name="acf[field_612f30685384d]" value="870">	<div class="show-if-value image-wrap" style="max-width: 300px">
		<img src=“{url_to_image}“ alt="" data-name="image" style="max-height: 300px;">
		<div class="acf-actions -hover">
						<a class="acf-icon -pencil dark" data-name="edit" href="#" title="Edit"></a>
						<a class="acf-icon -cancel dark" data-name="remove" href="#" title="Remove"></a>
		</div>
	</div>
	<div class="hide-if-value">
						<p>No image selected <a data-name="add" class="acf-button button" href="#">Add Image</a></p>
			</div>
</div>
			</div>
</div>



multilingual image field

<div class="acf-field acf-field-qtranslate-image acf-field-612f30685384d" style="width: 20%; min-height: 245px;" data-name="popup_img" data-type="qtranslate_image" data-key="field_612f30685384d" data-width="20" data-conditions="[[{&quot;field&quot;:&quot;field_612ddaedec092&quot;,&quot;operator&quot;:&quot;==&quot;,&quot;value&quot;:&quot;1&quot;}]]">
<div class="acf-label">
<label for="acf-field_612f30685384d">Popup Img</label></div>
<div class="acf-input">
<div class="multi-language-field multi-language-field-image"><a class="wp-switch-editor" data-language="es">Español</a><a class="wp-switch-editor current-language" data-language="en">English</a>            <div class="acf-image-uploader acf-cf has-value" data-preview_size="thumbnail" data-library="all" data-mime_types="" data-uploader="wp" data-language="es">
                <input type="hidden" name="acf[field_612f30685384d][es]" value="870">                <div class="show-if-value image-wrap" style="max-width: 150px">
                    <img data-name="image" src="{url_to_image}" alt="">
                    <div class="acf-actions -hover">
                        <a class="acf-icon -pencil dark" data-name="edit" href="#" title="Edit"></a><a class="acf-icon -cancel dark" data-name="remove" href="#" title="Remove"></a>
                    </div>
                </div>
                <div class="hide-if-value">
                    
                        <p>No image selected <a data-name="add" class="acf-button button" href="#">Add Image</a>
                        </p>

                                    </div>
            </div>

                    <div class="acf-image-uploader acf-cf has-value current-language" data-preview_size="thumbnail" data-library="all" data-mime_types="" data-uploader="wp" data-language="en">
                <input type="hidden" name="acf[field_612f30685384d][en]" value="870">                <div class="show-if-value image-wrap" style="max-width: 150px">
                    <img data-name="image" src="https://www.chiclanawifi.es/wp-content/uploads/2022/10/halloween-150x150.jpeg" alt="">
                    <div class="acf-actions -hover">
                        <a class="acf-icon -pencil dark" data-name="edit" href="#" title="Edit"></a><a class="acf-icon -cancel dark" data-name="remove" href="#" title="Remove"></a>
                    </div>
                </div>
                <div class="hide-if-value">
                    
                        <p>No image selected <a data-name="add" class="acf-button button" href="#">Add Image</a>
                        </p>

                                    </div>
            </div>

        </div></div>
</div>

**Comment by gab1982** [comment] 2022-11-05 21:13
> I guess it worked with ACF5 and it's a recent regression with ACF6? I'd need to bisect the differences between ACF 5 and 6 but I suspect something about the type of uploader.

Yes it worked fine with wp v5

**Comment by MKRD-SUPPORT** [comment] 2022-11-14 12:58
Strange, why is this working for me?

WP 6.1
ACF PRO 6.0.4
QTX 3.12.1

**Test:** Image (QTX), Group (ACF) + Image (QTX)

- option page
- page
- post

_Can you post your field group definition?_

**Comment by herrvigg** [comment] 2022-11-29 23:07
@gab1982 I can't reproduce the problem either, but I updated the rendering of the ACF-QTX image field, hoping it could solve the problem for you.
Could you try again using the last version available on master? It requires git or a manual installation. You can download a zip from the "code" button or here:
https://github.com/qtranslate/qtranslate-xt/archive/refs/heads/master.zip

**Comment by herrvigg** [comment] 2022-12-23 11:00
Released in 3.13.0.
Not clear if this fixes the issue but for now this is the best we can do. I close the ticket, re-open if it's still failing.

**Closed by herrvigg** 2022-12-23 11:00 UTC
Labels: need info, module: ACF
