### ISSUE TITLE
Permalinks give blank page

### ISSUE THREAD

**Issue by eirikvold** [qtranslate/qtranslate-xt#646] opened 2019-02-28 11:20 UTC
wp-admin/options-permalink.php gives blank page
If I deactivate qtranslate-xt it works again

**Comment by eirikvold** [comment] 2019-02-28 11:38
I updated WP Core  'wp-admin/inludes/misc.php' as a temporarily fix

` function got_mod_rewrite() { 
     //$got_rewrite = apache_mod_loaded('mod_rewrite', true); 
     //old line with false negative; 
     $got_rewrite = true;
     //force the response to true as we know mod_rewite is installed; 
     return apply_filters('got_rewrite', $got_rewrite); }`

**Comment by herrvigg** [comment] 2019-03-04 00:03
I'm using mostly nginx and not Apache, but i tried on a test configuration with Apache and i didn't have this problem, the permalink page works fine without change. I checked what `apache_mod_loaded` gives and it returns `true`. So this looks like a very specific issue.

From what i understand your problem comes from the call to that function. Can you try calling `apache_mod_loaded`  from another page, with qTranslate-XT enabled?

**Comment by herrvigg** [comment] 2019-03-06 10:35
@eirikvold can you try this by calling `apache_mod_loaded` from a page other than `options-permalink.php`? We need to understand better if it comes from a configuration issue with apache or something here.

The only related change i see could come from the fix for the REST API. See the new function `qtranxf_rest_api_register_rewrites` in qtranslate_core.php. But this seems to work well for all until now.

https://github.com/qtranslate/qtranslate-xt/commit/69c44d3691c9afc557d63567264626a2683f8cf8

**Comment by herrvigg** [comment] 2019-03-30 23:54
@eirikvold sorry i can't reproduce this problem so i close this. Feel free to re-open if you can provide more information.

**Closed by herrvigg** 2019-03-30 23:54 UTC
Labels: question
