### ISSUE TITLE
Add trailing slash on front page language URLS

### ISSUE THREAD

**Issue by bagaweb** [qtranslate/qtranslate-xt#660] opened 2019-04-02 14:06 UTC
A couple of SEO checking tools resulted in an error like www.mysite.com/de should look like www.mysite.com/de/ with a trailing slash.

I tried to modify the file qtranslate_frontend.php at line with the following code

`	
		if (is_front_page()) {
		$item->url = qtranxf_convertURL( $url, $lang, false, true ).'/';
		} else {
		$item->url = qtranxf_convertURL( $url, $lang, false, true );
		}
		`
Do you think this can be obtained in a better way?

**Comment by herrvigg** [comment] 2019-04-04 12:06
I don't know, this should work technically speaking but it depends where it's done and for what. Which SEO tool are you using? Do you have a SEO plugin with WP such as Yoast or All in one SEO?

**Comment by herrvigg** [comment] 2019-04-09 21:15
I used to have some issues with Google search and canonical URLs on some pages but eventually i managed to solve them all by setting the right value with `<link rel="canonical" href="url-value">` in the HTML header.

At this point i can't exactly tell if qTranslate-XT is doing something wrong, all i know is that nothing prevents to fix it. From what i have seen Yoast and other SEO plugins can have side effects because they rewrite this canonical link item.

Would it be possible to describe more precisely the problem?

**Comment by herrvigg** [comment] 2019-04-09 21:25
There can be very tricky cases depending what you want as canonical. For example the default canonical might change on the same page might change depending on the language stored in your client cookie. Also, the trailing slash can be handled/disturbed by rewrite rules defined in your HTTP server (apache, nginx).

**Comment by bagaweb** [comment] 2019-04-10 09:06
I tried on a fresh installation with default twentynineteen theme and everything was working fine, afterwards I found out the culprit, it's the plugin qTranslate slug who removes the trailing slashes. Do you think you'll be able to add the slug functionality in qTranslate-XT by default?

**Comment by herrvigg** [comment] 2019-04-10 22:27
No plan for the slugs yet, at least from my side. For those interested, there's work in progress in the `dev` folder but i haven't looked at it. The other way would be to integrate the dedicated plugin. But honestly i think the current state doesn't allow to add such a core functionality without big headaches.

About the trailing slash, i'll try to take a closer look. If we assume it's a bug in qTranslate, it's a good example of stuff that has to be fixed before looking into new features manipulating the URLs. Otherwise you will likely end up to chase regressions constantly.

**Comment by bagaweb** [comment] 2019-04-11 08:04
I think the bug is only the old qTranslate slug that I'm using (Version 1.1.18).
How can I test the stuff in the dev folder?
Thanks for your feedback!

**Comment by herrvigg** [comment] 2019-04-11 09:03
Oh if you have the qTranslate slug plugin that could have some impacts for sure. I don't use it. Could you disactivate is and tell if you still see the initial problem you are mentioning? In this case you should open a ticket on that plugin.

To test the dev/slugs folder, include the entry file at the end of `qtranslate.php` like this: 
```
require_once( QTRANSLATE_DIR . '/dev/slugs/qtx_slug.php' );
```
You can create a local branch in your repo for experiments or clone the whole project.

**Comment by bagaweb** [comment] 2019-04-12 08:56
>  Could you disactivate it and tell if you still see the initial problem you are mentioning?
Yes I wrote a few posts above, the problem doesn't happen without the qTranslate slug plugin.

> To test the dev/slugs folder, include the entry file at the end of qtranslate.php like this:

`require_once( QTRANSLATE_DIR . '/dev/slugs/qtx_slug.php' );`

Tried this but nothing happened, no slugs to edit anywhere... Am I doing something wrong?

**Comment by herrvigg** [comment] 2019-04-12 09:24
OK good, so i can close this ticket. But you can still comment on it.

About the dev slugs in qTranslate, i don't know the exact status. It would have been merged in the main code if it were working so no surprise things don't work there yet. If i remember some discussions it was a slightly different approach than the main slug plugin, but this dev code could still be useful to develop this feature properly.

**Closed by herrvigg** 2019-04-12 09:24 UTC

**Comment by bagaweb** [comment] 2019-04-12 09:26
Alright thanks for your time Herr Vigg.

**Comment by herrvigg** [comment] 2019-04-12 09:31
People wanting this feature should definitely look at both things, but maybe the easiest is to understand first what is missing in the slugs plugin and then we can try to merge it as a core feature in qTranslate, if their authors accept. It would be good to have them involved directly here. Discussions and experiments can start but i suggest we don't merge anything before we have migrated this repo to a new plugin.

**Comment by bagaweb** [comment] 2019-04-12 09:38
That old pugin works fine apart from this little problem of the trailing slash in the front page.

Do you think we should try to contact the authors?

https://github.com/LC43/

https://github.com/not-only-code

**Comment by herrvigg** [comment] 2019-04-12 09:59
qTranslate slugs has not been updated for 3 years, it has a lot of bugs:
https://wordpress.org/support/plugin/qtranslate-slug/

Is this repo the reference source? See the last update and the number of issues.
https://github.com/not-only-code/qtranslate-slug

I will definitely not merge a plugin in that state, better to keep it separated at this point. What you can do is start to contact them on their repos and tell we are reviving qTranslate(-X/XT) so they can also start to revive their stuff ;)

**Comment by bagaweb** [comment] 2019-04-12 10:13
Well it works fine for me even on a large website in 10 different langauges with more than 200 pages and 10 different custom post types running on PHP 7.3.

**Comment by herrvigg** [comment] 2019-04-12 10:19
Good to hear! Maybe the authors somehow abandoned their plugins with regards to qTranslate-X. Now that we are giving it a new life its state should be reviewed. If these are small bugs or corner cases it's fine but some cleanup has to be done at least in the tickets.
